plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.2'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'war'
}

group = 'com.woori'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        // compileOnly 설정에 annotationProcessor 의존성 포함
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral() // 이제 settings.gradle에서 허용했으므로 에러가 나지 않습니다.
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation' // Validation 추가

    compileOnly 'org.projectlombok:lombok'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    // runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
    implementation 'com.mysql:mysql-connector-j:8.4.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    //추가 라이브러리(mvnrepository.com)
    //변환처리
    implementation 'org.modelmapper:modelmapper:3.1.1'
    //레이아웃
    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect'

    //AWS S3(서버구동시 적용)
//	compileOnly 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'
    // https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-s3
//	implementation 'com.amazonaws:aws-java-sdk-s3:1.12.773'


    providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
    implementation 'com.googlecode.json-simple:json-simple:1.1.1'

    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.3'

    implementation 'org.springframework.boot:spring-boot-starter-mail'

    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

    // 데이터 불량 검문소
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // swagger
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'
    // Swagger UI (자동 문서화 도구)
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'
    // PDF 텍스트 추출용 (Apache PDFBox)
    implementation 'org.apache.pdfbox:pdfbox:2.0.30'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
    // pgvector
    implementation files('libs/pgvector-java-0.1.6.jar')
    // postgresql
    runtimeOnly 'org.postgresql:postgresql'

    implementation 'com.solapi:sdk:1.0.3'

    // resilience4j : 타임아웃 + 서킷브레이크 설정을 위한 의존성
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'io.github.resilience4j:resilience4j-spring-boot3:2.1.0'
}


tasks.named('test') {
    useJUnitPlatform()
}
