package com.example.pproject.notification.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;

/**
 * 알림 템플릿 엔티티
 * 
 * ========================================
 * ERD 테이블: notification_template (37번)
 * ========================================
 * 
 * 컬럼 매핑:
 * - template_id     -> id (PK, BIGINT GENERATED BY DEFAULT AS IDENTITY)
 * - template_code   -> templateCode (VARCHAR(50) NOT NULL, UNIQUE)
 * - channel         -> channel (VARCHAR(20) NOT NULL, CHECK: EMAIL/SMS/PUSH)
 * - subject         -> subject (VARCHAR(200) NULL)
 * - body            -> body (TEXT NOT NULL)
 * - created_at      -> createdAt (TIMESTAMPTZ(3) NOT NULL DEFAULT now())
 * 
 * 제약조건:
 * - CONSTRAINT uq_notification_template_code UNIQUE (template_code)
 * - CONSTRAINT ck_notification_channel CHECK (channel IN ('EMAIL','SMS','PUSH'))
 */
@Entity
@Table(name = "notification_template")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class NotificationTemplate {

    /**
     * PK: template_id (BIGINT GENERATED BY DEFAULT AS IDENTITY)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "template_id")
    private Long id;

    /**
     * 템플릿 코드 (VARCHAR(50) NOT NULL, UNIQUE)
     * - 알림 유형을 식별하는 고유 코드
     * - 예: APPLICATION_SUBMITTED, INTERVIEW_SCHEDULED 등
     */
    @Column(name = "template_code", nullable = false, length = 50, unique = true)
    private String templateCode;

    /**
     * 발송 채널 (VARCHAR(20) NOT NULL)
     * - CHECK: EMAIL, SMS, PUSH
     */
    @Column(name = "channel", nullable = false, length = 20)
    @Enumerated(EnumType.STRING)
    private NotificationChannel channel;

    /**
     * 제목 (VARCHAR(200) NULL)
     * - EMAIL의 경우 이메일 제목
     * - PUSH의 경우 푸시 알림 제목
     * - SMS는 NULL 가능
     */
    @Column(name = "subject", length = 200)
    private String subject;

    /**
     * 본문 (TEXT NOT NULL)
     * - 플레이스홀더 지원: {{userName}}, {{jobTitle}} 등
     */
    @Column(name = "body", columnDefinition = "TEXT", nullable = false)
    private String body;

    /**
     * 생성일시 (TIMESTAMPTZ(3) NOT NULL DEFAULT now())
     */
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    @PrePersist
    void prePersist() {
        if (createdAt == null) {
            createdAt = Instant.now();
        }
    }

    /**
     * 알림 채널 Enum
     * - ERD CHECK: channel IN ('EMAIL','SMS','PUSH')
     */
    public enum NotificationChannel {
        EMAIL,
        SMS,
        PUSH
    }
}
