package com.example.pproject.notification.entity;

import com.example.pproject.user.entity.UserEntity;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;

/**
 * 알림 발송 이력 엔티티
 * 
 * ========================================
 * ERD 테이블: notification_delivery (38번)
 * ========================================
 * 
 * 컬럼 매핑:
 * - delivery_id   -> id (PK, BIGINT GENERATED BY DEFAULT AS IDENTITY)
 * - template_id   -> template (FK -> notification_template.template_id, NULL 허용)
 * - member_id     -> member (FK -> member.member_id, NOT NULL)
 * - event_type    -> eventType (VARCHAR(40) NOT NULL)
 * - channel       -> channel (VARCHAR(20) NOT NULL, CHECK: EMAIL/SMS/PUSH)
 * - status        -> status (VARCHAR(20) NOT NULL DEFAULT 'PENDING', CHECK: PENDING/SENT/FAILED)
 * - sent_at       -> sentAt (TIMESTAMPTZ(3) NULL)
 * - payload       -> payload (JSONB NULL)
 * - created_at    -> createdAt (TIMESTAMPTZ(3) NOT NULL DEFAULT now())
 * 
 * 제약조건:
 * - CONSTRAINT ck_notification_delivery_status CHECK (status IN ('PENDING','SENT','FAILED'))
 * - CONSTRAINT ck_notification_delivery_channel CHECK (channel IN ('EMAIL','SMS','PUSH'))
 * 
 * FK 관계:
 * - template_id -> notification_template(template_id)
 * - member_id -> member(member_id)
 */
@Entity
@Table(name = "notification_delivery")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class NotificationDelivery {

    /**
     * PK: delivery_id (BIGINT GENERATED BY DEFAULT AS IDENTITY)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "delivery_id")
    private Long id;

    /**
     * FK: template_id -> notification_template(template_id)
     * - NULL 허용 (템플릿 없이 직접 발송 가능)
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "template_id")
    private NotificationTemplate template;

    /**
     * FK: member_id -> member(member_id) NOT NULL
     * - 알림 수신 대상 회원
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id", nullable = false)
    private UserEntity member;

    /**
     * 이벤트 타입 (VARCHAR(40) NOT NULL)
     * - 알림을 발생시킨 이벤트 종류
     * - 예: APPLICATION_SUBMITTED, INTERVIEW_SCHEDULED, PAYMENT_COMPLETED 등
     */
    @Column(name = "event_type", nullable = false, length = 40)
    private String eventType;

    /**
     * 발송 채널 (VARCHAR(20) NOT NULL)
     * - CHECK: EMAIL, SMS, PUSH
     */
    @Column(name = "channel", nullable = false, length = 20)
    @Enumerated(EnumType.STRING)
    private NotificationTemplate.NotificationChannel channel;

    /**
     * 발송 상태 (VARCHAR(20) NOT NULL DEFAULT 'PENDING')
     * - CHECK: PENDING, SENT, FAILED
     */
    @Column(name = "status", nullable = false, length = 20)
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private DeliveryStatus status = DeliveryStatus.PENDING;

    /**
     * 발송 일시 (TIMESTAMPTZ(3) NULL)
     * - 실제 발송 완료된 시각
     */
    @Column(name = "sent_at")
    private Instant sentAt;

    /**
     * 페이로드 (JSONB NULL)
     * - 알림에 포함된 동적 데이터
     * - 예: {"jobTitle": "백엔드 개발자", "companyName": "ABC Company"}
     * 
     * Hibernate JSON 타입 매핑:
     * - @JdbcTypeCode(SqlTypes.JSON): String 타입을 PostgreSQL JSONB로 자동 변환
     * - JSON 문자열을 그대로 저장하되 DB에서는 JSONB 타입으로 처리
     */
    @Column(name = "payload", columnDefinition = "JSONB")
    @JdbcTypeCode(SqlTypes.JSON)
    private String payload;

    /**
     * 생성일시 (TIMESTAMPTZ(3) NOT NULL DEFAULT now())
     */
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    /**
     * 읽음 여부 (프론트엔드 표시용 - ERD에는 없지만 기능 필요)
     */
    @Column(name = "is_read", nullable = false)
    @Builder.Default
    private Boolean isRead = false;

    /**
     * 링크 URL (프론트엔드 이동용 - ERD에는 없지만 기능 필요)
     */
    @Column(name = "link_url", length = 500)
    private String linkUrl;

    @PrePersist
    void prePersist() {
        if (createdAt == null) {
            createdAt = Instant.now();
        }
        if (status == null) {
            status = DeliveryStatus.PENDING;
        }
        if (isRead == null) {
            isRead = false;
        }
    }

    /**
     * 발송 상태 Enum
     * - ERD CHECK: status IN ('PENDING','SENT','FAILED')
     */
    public enum DeliveryStatus {
        PENDING,  // 발송 대기
        SENT,     // 발송 완료
        FAILED    // 발송 실패
    }

    /**
     * 발송 완료 처리
     */
    public void markAsSent() {
        this.status = DeliveryStatus.SENT;
        this.sentAt = Instant.now();
    }

    /**
     * 발송 실패 처리
     */
    public void markAsFailed() {
        this.status = DeliveryStatus.FAILED;
    }

    /**
     * 읽음 처리
     */
    public void markAsRead() {
        this.isRead = true;
    }
}
