-- ================================
-- MERGED POSTGRESQL SCHEMA (Idempotent Version)
-- 수정내용: 이미 존재할 경우 스킵(IF NOT EXISTS) 처리 적용
-- ================================

-- 1. Extensions (이미 IF NOT EXISTS가 적용되어 있음)
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. Functions (OR REPLACE는 덮어쓰기 허용이므로 유지, 필요 시 로직 변경 가능)
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


/* =========================================================
 * 1) member
 * ========================================================= */
CREATE TABLE IF NOT EXISTS member (
  member_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_uid              UUID NOT NULL,
  email                   VARCHAR(320) NOT NULL,
  login_id                VARCHAR(50) NULL,
  auth_provider           VARCHAR(20) NOT NULL DEFAULT 'OTHER',
  password_hash           VARCHAR(255) NULL,
  name                    VARCHAR(80) NOT NULL,
  gender                  VARCHAR(20) NULL,
  birth_date              DATE NULL,
  phone                   VARCHAR(20) NULL,
  role                    VARCHAR(20) NOT NULL,
  status                  VARCHAR(20) NOT NULL,
  last_login_at           TIMESTAMPTZ(3) NULL,
  password_changed_at     TIMESTAMPTZ(3) NULL,
  failed_login_count      INT NOT NULL DEFAULT 0,
  locked_until            TIMESTAMPTZ(3) NULL,
  phone_verified_at       TIMESTAMPTZ(3) NULL,
  created_at              TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at              TIMESTAMPTZ(3) NULL,
  terms_notice_id         BIGINT NULL,
  terms_agreed_at         TIMESTAMPTZ(3) NULL,
  privacy_notice_id       BIGINT NULL,
  privacy_agreed_at       TIMESTAMPTZ(3) NULL,
  policy_notice_id        BIGINT NULL,
  policy_agreed_at        TIMESTAMPTZ(3) NULL,
  marketing_opt_in        BOOLEAN NOT NULL DEFAULT FALSE,
  marketing_agreed_at     TIMESTAMPTZ(3) NULL,
  consent_ip              VARCHAR(45) NULL,
  consent_user_agent      TEXT NULL,

  CONSTRAINT uq_member_uid UNIQUE (member_uid),
  CONSTRAINT uq_member_email UNIQUE (email),

  CONSTRAINT ck_member_role
    CHECK (role IN ('CANDIDATE','EMPLOYER','SERVICEADMIN','APPROVEADMIN','MASTER')),
  CONSTRAINT ck_member_status
    CHECK (status IN ('ACTIVE','SUSPENDED','WITHDRAWN')),
  CONSTRAINT ck_member_failed_login_count
    CHECK (failed_login_count >= 0),
  CONSTRAINT ck_member_auth_provider
    CHECK (auth_provider IN ('NAVER','GOOGLE','KAKAO','OTHER')),
  CONSTRAINT ck_member_gender
    CHECK (gender IS NULL OR gender IN ('MALE','FEMALE')),
  CONSTRAINT ck_member_phone_verified_requires_phone
    CHECK (phone_verified_at IS NULL OR phone IS NOT NULL),
  CONSTRAINT ck_member_required_consents
    CHECK (
      status <> 'ACTIVE'
      OR (
        terms_notice_id   IS NOT NULL AND terms_agreed_at   IS NOT NULL AND
        privacy_notice_id IS NOT NULL AND privacy_agreed_at IS NOT NULL
      )
    ),
  CONSTRAINT ck_member_marketing_optin_time
    CHECK (
      marketing_opt_in IS FALSE
      OR (marketing_opt_in IS TRUE AND marketing_agreed_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_member_login_id_active
  ON member (login_id)
  WHERE deleted_at IS NULL AND login_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_member_phone_verified_active
  ON member (phone)
  WHERE deleted_at IS NULL
    AND phone IS NOT NULL
    AND phone_verified_at IS NOT NULL;


/* =========================================================
 * 1-1) phone_verification
 * ========================================================= */
CREATE TABLE IF NOT EXISTS phone_verification (
  verification_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phone               VARCHAR(20) NOT NULL,
  purpose             VARCHAR(20) NOT NULL,
  code_hash           CHAR(64) NOT NULL,
  expires_at          TIMESTAMPTZ(3) NOT NULL,
  verified_at         TIMESTAMPTZ(3) NULL,
  consumed_at         TIMESTAMPTZ(3) NULL,
  attempt_count       INT NOT NULL DEFAULT 0,
  resend_count        INT NOT NULL DEFAULT 0,
  last_sent_at        TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  request_ip          VARCHAR(45) NULL,
  request_user_agent  TEXT NULL,
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_phone_verification_purpose
    CHECK (purpose IN ('SIGNUP','PASSWORD_RESET','PHONE_LINK')),
  CONSTRAINT ck_phone_verification_attempt
    CHECK (attempt_count >= 0),
  CONSTRAINT ck_phone_verification_resend
    CHECK (resend_count >= 0),
  CONSTRAINT ck_phone_verification_phone_digits
    CHECK (phone ~ '^[0-9]{10,15}$')
);

CREATE INDEX IF NOT EXISTS idx_phone_verification_phone_purpose_created
  ON phone_verification(phone, purpose, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_phone_verification_active
  ON phone_verification(phone, purpose, expires_at)
  WHERE consumed_at IS NULL;


/* =========================================================
 * 2) member_login_log
 * ========================================================= */
CREATE TABLE IF NOT EXISTS member_login_log (
  login_log_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id       BIGINT NOT NULL REFERENCES member(member_id),
  success         BOOLEAN NOT NULL DEFAULT FALSE,
  ip_address      VARCHAR(45) NULL,
  user_agent      TEXT NULL,
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_member_login_log_member_created
  ON member_login_log(member_id, created_at DESC);


/* =========================================================
 * 3) employer
 * ========================================================= */
CREATE TABLE IF NOT EXISTS employer (
  employer_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_uid    UUID NOT NULL,
  name            VARCHAR(120) NOT NULL,
  logo_url        TEXT NULL,
  industry        VARCHAR(80) NULL,
  founded_year    INT NULL,
  employee_count  INT NULL,
  location        VARCHAR(120) NULL,
  description     TEXT NULL,
  culture         TEXT NULL,
  benefits        TEXT NULL,
  tech_stack      TEXT NULL,
  contact_email   VARCHAR(320) NULL,
  contact_phone   VARCHAR(20) NULL,
  website_url     TEXT NULL,
  status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at      TIMESTAMPTZ(3) NULL,

  CONSTRAINT uq_employer_uid UNIQUE (employer_uid),
  CONSTRAINT ck_employer_status CHECK (status IN ('ACTIVE','SUSPENDED','CLOSED'))
);

CREATE INDEX IF NOT EXISTS idx_employer_name ON employer(name);


/* =========================================================
 * 4) employer_member
 * ========================================================= */
CREATE TABLE IF NOT EXISTS employer_member (
  employer_member_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id          BIGINT NOT NULL REFERENCES employer(employer_id),
  member_id            BIGINT NOT NULL REFERENCES member(member_id),
  role_in_company      VARCHAR(20) NOT NULL,
  active               BOOLEAN NOT NULL DEFAULT TRUE,
  created_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_employer_member UNIQUE (employer_id, member_id),
  CONSTRAINT ck_role_in_company CHECK (role_in_company IN ('OWNER','HR','STAFF'))
);


/* =========================================================
 * 5) product
 * ========================================================= */
CREATE TABLE IF NOT EXISTS product (
  product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_code    VARCHAR(40) NOT NULL,
  product_type    VARCHAR(20) NOT NULL,
  name            VARCHAR(120) NOT NULL,
  sale_status     VARCHAR(20) NOT NULL,
  price_amount    NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  currency        CHAR(3) NOT NULL DEFAULT 'KRW',
  credit_amount   INT NULL,
  plan_tier       VARCHAR(20) NULL,
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at      TIMESTAMPTZ(3) NULL,

  CONSTRAINT uq_product_code UNIQUE (product_code),
  CONSTRAINT ck_product_type CHECK (product_type IN ('ONE_TIME','SUBSCRIPTION')),
  CONSTRAINT ck_sale_status CHECK (sale_status IN ('ON_SALE','PAUSED','STOPPED'))
);


/* =========================================================
 * 6) orders
 * ========================================================= */
CREATE TABLE IF NOT EXISTS orders (
  order_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_uid           UUID NOT NULL,
  buyer_type          VARCHAR(20) NOT NULL,
  buyer_member_id     BIGINT NULL REFERENCES member(member_id),
  buyer_employer_id   BIGINT NULL REFERENCES employer(employer_id),
  product_id          BIGINT NOT NULL REFERENCES product(product_id),
  order_amount        NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  status              VARCHAR(20) NOT NULL DEFAULT 'CREATED',
  idempotency_key     VARCHAR(64) NOT NULL,
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_order_uid UNIQUE (order_uid),
  CONSTRAINT uq_orders_idempotency UNIQUE (idempotency_key),
  CONSTRAINT ck_orders_buyer_type CHECK (buyer_type IN ('MEMBER','EMPLOYER')),
  CONSTRAINT ck_orders_status CHECK (status IN ('CREATED','PAID','CANCELED','FAILED')),
  CONSTRAINT ck_orders_buyer_fk
    CHECK (
      (buyer_type = 'MEMBER'   AND buyer_member_id IS NOT NULL AND buyer_employer_id IS NULL) OR
      (buyer_type = 'EMPLOYER' AND buyer_employer_id IS NOT NULL AND buyer_member_id IS NULL)
    )
);


/* =========================================================
 * 7) payment
 * ========================================================= */
CREATE TABLE IF NOT EXISTS payment (
  payment_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_uid         UUID NOT NULL,
  order_id            BIGINT NOT NULL REFERENCES orders(order_id),
  method              VARCHAR(20) NOT NULL,
  paid_amount         NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  app_status          VARCHAR(30) NOT NULL DEFAULT 'REQUESTED',
  pg_status           VARCHAR(40) NULL,
  pg_payment_key      VARCHAR(100) NULL,
  pg_approval_key     VARCHAR(80) NULL,
  pg_transaction_id   VARCHAR(80) NULL,
  pg_payload          JSONB NULL,
  approved_at         TIMESTAMPTZ(3) NULL,
  canceled_at         TIMESTAMPTZ(3) NULL,
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_payment_uid UNIQUE (payment_uid),
  CONSTRAINT ck_payment_app_status
    CHECK (app_status IN ('REQUESTED','APPROVED','FAILED','CANCELED','PARTIAL_CANCELED')),
  CONSTRAINT ck_payment_pg_status
    CHECK (
      pg_status IS NULL OR
      pg_status IN (
        'READY','IN_PROGRESS','WAITING_FOR_DEPOSIT','DONE',
        'CANCELED','PARTIAL_CANCELED','ABORTED','EXPIRED'
      )
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_pg_payment_key
  ON payment(pg_payment_key)
  WHERE pg_payment_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_payment_order_id
  ON payment(order_id);


/* =========================================================
 * 8) pg_webhook_inbox
 * ========================================================= */
CREATE TABLE IF NOT EXISTS pg_webhook_inbox (
  inbox_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pg_event_id     VARCHAR(100) NOT NULL,
  event_type      VARCHAR(120) NOT NULL,
  payment_id      BIGINT NULL REFERENCES payment(payment_id),
  payload         JSONB NOT NULL,
  process_status  VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
  retry_count     INT NOT NULL DEFAULT 0,
  last_error      TEXT NULL,
  received_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  processed_at    TIMESTAMPTZ(3) NULL,

  CONSTRAINT uq_pg_event_id UNIQUE (pg_event_id),
  CONSTRAINT ck_pg_webhook_process_status
    CHECK (process_status IN ('RECEIVED','PROCESSED','FAILED')),
  CONSTRAINT ck_pg_webhook_retry_count
    CHECK (retry_count >= 0)
);


/* =========================================================
 * 9) wallet
 * ========================================================= */
CREATE TABLE IF NOT EXISTS wallet (
  wallet_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_type     VARCHAR(20) NOT NULL,
  member_id      BIGINT NULL REFERENCES member(member_id),
  employer_id    BIGINT NULL REFERENCES employer(employer_id),
  balance        INT NOT NULL DEFAULT 0,
  status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_wallet_owner_type CHECK (owner_type IN ('MEMBER','EMPLOYER')),
  CONSTRAINT ck_wallet_owner_fk
    CHECK (
      (owner_type='MEMBER'   AND member_id IS NOT NULL AND employer_id IS NULL) OR
      (owner_type='EMPLOYER' AND employer_id IS NOT NULL AND member_id IS NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_wallet_member_one
  ON wallet(member_id) WHERE member_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_wallet_employer_one
  ON wallet(employer_id) WHERE employer_id IS NOT NULL;


/* =========================================================
 * 10) wallet_ledger
 * ========================================================= */
CREATE TABLE IF NOT EXISTS wallet_ledger (
  ledger_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id        BIGINT NOT NULL REFERENCES wallet(wallet_id),
  tx_type          VARCHAR(10) NOT NULL,
  source_type      VARCHAR(30) NOT NULL,
  source_ref_id    BIGINT NULL,
  amount           INT NOT NULL,
  balance_before   INT NOT NULL,
  balance_after    INT NOT NULL,
  idempotency_key  VARCHAR(100) NOT NULL,
  memo             VARCHAR(200) NULL,
  occurred_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_wallet_ledger_idem UNIQUE (idempotency_key),
  CONSTRAINT ck_wallet_ledger_tx_type CHECK (tx_type IN ('CREDIT','DEBIT')),
  CONSTRAINT ck_wallet_ledger_source_type
    CHECK (source_type IN ('PAYMENT','SUBSCRIPTION','AI','AD_CLICK','MANUAL'))

  , updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_wallet_ledger_wallet_occurred
  ON wallet_ledger(wallet_id, occurred_at DESC);


/* =========================================================
 * 11) subscription
 * ========================================================= */
CREATE TABLE IF NOT EXISTS subscription (
  subscription_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id      BIGINT NOT NULL REFERENCES employer(employer_id),
  product_id       BIGINT NOT NULL REFERENCES product(product_id),
  status           VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  started_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  next_billing_at  TIMESTAMPTZ(3) NULL,
  ended_at         TIMESTAMPTZ(3) NULL,
  customer_key     VARCHAR(80) NULL,
  billing_key      VARCHAR(200) NULL,
  created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_subscription_status CHECK (status IN ('ACTIVE','CANCELED','PAYMENT_FAILED'))
);


/* =========================================================
 * 12) subscription_billing_cycle
 * ========================================================= */
CREATE TABLE IF NOT EXISTS subscription_billing_cycle (
  cycle_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id  BIGINT NOT NULL REFERENCES subscription(subscription_id),
  billing_month    DATE NOT NULL,
  payment_id       BIGINT NULL REFERENCES payment(payment_id),
  credit_grant     INT NOT NULL,
  ledger_id        BIGINT NULL REFERENCES wallet_ledger(ledger_id),
  payment_status   VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
  credit_status    VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_subscription_billing UNIQUE (subscription_id, billing_month),
  CONSTRAINT ck_cycle_payment_status
    CHECK (payment_status IN ('SCHEDULED','PAID','FAILED')),
  CONSTRAINT ck_cycle_credit_status
    CHECK (credit_status IN ('PENDING','GRANTED','FAILED','REVOKED'))
);


/* =========================================================
 * 13) job_posting
 * ========================================================= */
CREATE TABLE IF NOT EXISTS job_posting (
  job_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id         BIGINT NOT NULL REFERENCES employer(employer_id),
  title               VARCHAR(200) NOT NULL,
  description         TEXT NOT NULL,
  status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  location            VARCHAR(120) NULL,
  salary_text         VARCHAR(80) NULL,
  required_questions  JSONB NULL,
  view_count          INT NOT NULL DEFAULT 0,
  apply_count         INT NOT NULL DEFAULT 0,
  stack              TEXT[] NULL,
  required_experience INT NOT NULL DEFAULT 0,
  summary             TEXT NULL,
  embedding           vector(1536) NULL,
  ad_bid_credit       INT NOT NULL DEFAULT 0,
  recruitment_capacity INT NOT NULL DEFAULT 0,
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at          TIMESTAMPTZ(3) NULL,

  CONSTRAINT ck_job_posting_status CHECK (status IN ('DRAFT','OPEN','CLOSED')),
  CONSTRAINT ck_job_posting_counts CHECK (view_count >= 0 AND apply_count >= 0),
  CONSTRAINT ck_job_posting_ad_bid_credit_nonneg CHECK (ad_bid_credit >= 0),
  CONSTRAINT ck_job_posting_recruitment_capacity CHECK (recruitment_capacity >= 0)
);

CREATE INDEX IF NOT EXISTS idx_job_posting_employer_status
  ON job_posting(employer_id, status);

CREATE INDEX IF NOT EXISTS idx_job_posting_stack_gin ON job_posting USING GIN (stack);

CREATE INDEX IF NOT EXISTS idx_job_posting_ads_prefilter
  ON job_posting (stack, ad_bid_credit DESC, job_id)
  WHERE deleted_at IS NULL
    AND status = 'OPEN'
    AND ad_bid_credit > 0;

COMMENT ON COLUMN job_posting.ad_bid_credit IS
'광고 입찰가(credit). RTB 우선순위/AI유사도+비즈가치 하이브리드 스코어/광고만 프리필터링 용도.';
COMMENT ON COLUMN job_posting.required_experience IS '채용을 위해 요구되는 최소 경력 연수 (0: 신입)';


/* =========================================================
 * 14) resume
 * ========================================================= */
CREATE TABLE IF NOT EXISTS resume (
  resume_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id            BIGINT NOT NULL REFERENCES member(member_id),
  title                VARCHAR(120) NOT NULL,
  tagline              VARCHAR(200) NULL,
  is_primary           BOOLEAN NOT NULL DEFAULT FALSE,
  is_public            BOOLEAN NOT NULL DEFAULT FALSE,
  status               VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  last_modified_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  created_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at           TIMESTAMPTZ(3) NULL,
  target_job_id        BIGINT NULL REFERENCES job_posting(job_id),
  content              TEXT NULL,
  field                VARCHAR(20) NOT NULL,
  summary              TEXT NULL,
  embedding            vector(1536) NULL,
  summary_status       VARCHAR(20) NOT NULL DEFAULT 'NONE',
  preference_location  VARCHAR(80) NULL,
  preference_salary    VARCHAR(80) NULL,
  employment_type      VARCHAR(80) NULL,
  re_stack            TEXT[] NULL,
  career_years         INT NOT NULL DEFAULT 0,
  school               TEXT NULL,
  school_state         TEXT NULL,
  school_class         TEXT NULL,

  CONSTRAINT ck_resume_status CHECK (status IN ('DRAFT','ACTIVE','DELETED')),
  CONSTRAINT ck_resume_field  CHECK (field IN ('RESUME','PORTFOLIO','INTRO')),
  CONSTRAINT ck_resume_summary_status
    CHECK (summary_status IN ('NONE','PENDING','PROCESSING','COMPLETED','FAILED')),
  CONSTRAINT ck_resume_summary_completed_has_summary
    CHECK (summary_status <> 'COMPLETED' OR summary IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_resume_member_status
  ON resume(member_id, status);

CREATE INDEX IF NOT EXISTS idx_resume_re_stack_gin ON resume USING GIN (re_stack);

CREATE INDEX IF NOT EXISTS idx_resume_summary_todo
  ON resume (summary_status, updated_at DESC, resume_id)
  WHERE summary_status IN ('PENDING','FAILED');

COMMENT ON COLUMN resume.summary_status IS 'AI 요약 비동기 상태: NONE(미요청)/PENDING/PROCESSING/COMPLETED/FAILED';
COMMENT ON COLUMN resume.re_stack IS '사용자가 보유한 기술 스택 목록 (배열)';
COMMENT ON COLUMN resume.career_years IS '사용자가 직접 입력/확정한 직무 관련 총 경력 연수';


/* =========================================================
 * 15) job_application
 * ========================================================= */
CREATE TABLE IF NOT EXISTS job_application (
  application_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id                BIGINT NOT NULL REFERENCES job_posting(job_id),
  member_id             BIGINT NOT NULL REFERENCES member(member_id),
  resume_id             BIGINT NOT NULL REFERENCES resume(resume_id),
  status                VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
  answers               JSONB NULL,
  applied_at            TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  canceled_at           TIMESTAMPTZ(3) NULL,
  viewed_at             TIMESTAMPTZ(3) NULL,
  contact_disclosed_at  TIMESTAMPTZ(3) NULL,
  created_at            TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_job_application UNIQUE (job_id, member_id),
  CONSTRAINT ck_job_application_status
    CHECK (status IN ('SUBMITTED','VIEWED','INTERVIEW','HIRED','REJECTED','CANCELED'))
);


/* =========================================================
 * 16) interview_schedule
 * ========================================================= */
CREATE TABLE IF NOT EXISTS interview_schedule (
  interview_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id       BIGINT NOT NULL REFERENCES job_application(application_id),
  stage                VARCHAR(20) NOT NULL,
  method               VARCHAR(20) NOT NULL,
  location             VARCHAR(200) NULL,
  meeting_url          TEXT NULL,
  start_at             TIMESTAMPTZ(3) NOT NULL,
  end_at               TIMESTAMPTZ(3) NOT NULL,
  status               VARCHAR(20) NOT NULL DEFAULT 'PROPOSED',
  created_by_member_id BIGINT NULL REFERENCES member(member_id),
  created_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_interview_stage CHECK (stage IN ('1ST','2ND','FINAL')),
  CONSTRAINT ck_interview_method CHECK (method IN ('ONSITE','VIDEO','PHONE')),
  CONSTRAINT ck_interview_status CHECK (status IN ('PROPOSED','CONFIRMED','CANCELED','DONE')),
  CONSTRAINT ck_interview_time CHECK (end_at > start_at)
);


/* =========================================================
 * 17) interview_response
 * ========================================================= */
CREATE TABLE IF NOT EXISTS interview_response (
  response_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interview_id    BIGINT NOT NULL REFERENCES interview_schedule(interview_id),
  response        VARCHAR(20) NOT NULL,
  message         TEXT NULL,
  responded_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_interview_response CHECK (response IN ('ACCEPT','DECLINE','REQUEST_CHANGE'))
);


/* =========================================================
 * 18) resume_profile
 * ========================================================= */
CREATE TABLE IF NOT EXISTS resume_profile (
  profile_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id    BIGINT NOT NULL REFERENCES resume(resume_id),
  address      VARCHAR(200) NULL,
  photo_url    TEXT NULL,
  created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_resume_profile UNIQUE (resume_id)
);


/* =========================================================
 * 19) resume_project
 * ========================================================= */
CREATE TABLE IF NOT EXISTS resume_project (
  project_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id           BIGINT NOT NULL REFERENCES resume(resume_id),
  title               VARCHAR(120) NOT NULL,
  start_date          DATE NULL,
  end_date            DATE NULL,
  contribution_pct    NUMERIC(5,2) NULL,
  tech_stack          TEXT[] NULL,
  description         TEXT NULL,
  sort_order          INT NOT NULL DEFAULT 0,
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);


/* =========================================================
 * 20) resume_attachment
 * ========================================================= */
CREATE TABLE IF NOT EXISTS resume_attachment (
  attachment_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id       BIGINT NOT NULL REFERENCES resume(resume_id),
  file_url        TEXT NOT NULL,
  file_name       VARCHAR(200) NOT NULL,
  mime_type       VARCHAR(80) NULL,
  file_size       BIGINT NULL,
  scan_status     VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  copyright_ok    BOOLEAN NOT NULL DEFAULT FALSE,
  ai_description  TEXT NULL,
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_resume_attachment_scan_status CHECK (scan_status IN ('PENDING','PASSED','FAILED'))
);


/* =========================================================
 * 21) resume_link
 * ========================================================= */
CREATE TABLE IF NOT EXISTS resume_link (
  link_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id    BIGINT NOT NULL REFERENCES resume(resume_id),
  link_type    VARCHAR(20) NOT NULL,
  url          TEXT NOT NULL,
  created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_resume_link_type CHECK (link_type IN ('GITHUB','BLOG','ETC'))
);


/* =========================================================
 * 22) resume_career
 * ========================================================= */
CREATE TABLE IF NOT EXISTS resume_career (
  career_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id       BIGINT NOT NULL REFERENCES resume(resume_id),
  company_name    VARCHAR(100) NOT NULL,
  department      VARCHAR(100) NOT NULL,
  role            VARCHAR(100) NOT NULL,
  start_date      DATE NOT NULL,
  end_date        DATE NULL,
  is_current      BOOLEAN NULL,
  is_verified     BOOLEAN NULL,
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_resume_career_dates
    CHECK (
      (is_current IS TRUE AND end_date IS NULL)
      OR (is_current IS DISTINCT FROM TRUE AND (end_date IS NULL OR end_date >= start_date))
    )
);

CREATE INDEX IF NOT EXISTS idx_resume_career_resume_id ON resume_career(resume_id);


/* =========================================================
 * 23) resume_certificate
 * ========================================================= */
CREATE TABLE IF NOT EXISTS resume_certificate (
  resume_certificate_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id              BIGINT NOT NULL REFERENCES resume(resume_id),
  name                   VARCHAR(100) NOT NULL,
  issuer                 VARCHAR(100) NOT NULL,
  acquisition_date       DATE NOT NULL,
  is_verified            BOOLEAN NULL,
  created_at             TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_resume_certificate_resume_id ON resume_certificate(resume_id);


/* =========================================================
 * 24) job_scrap
 * ========================================================= */
CREATE TABLE IF NOT EXISTS job_scrap (
  scrap_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id    BIGINT NOT NULL REFERENCES member(member_id),
  job_id       BIGINT NOT NULL REFERENCES job_posting(job_id),
  created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_job_scrap UNIQUE (member_id, job_id)
);


/* =========================================================
 * 25) job_view_log
 * ========================================================= */
CREATE TABLE IF NOT EXISTS job_view_log (
  view_log_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id    BIGINT NULL REFERENCES member(member_id),
  job_id       BIGINT NOT NULL REFERENCES job_posting(job_id),
  viewed_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);


/* =========================================================
 * 26) ad_campaign
 * ========================================================= */
CREATE TABLE IF NOT EXISTS ad_campaign (
  campaign_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id    BIGINT NOT NULL REFERENCES employer(employer_id),
  job_id         BIGINT NOT NULL REFERENCES job_posting(job_id),
  cpc_bid        INT NOT NULL,
  daily_budget   INT NOT NULL,
  status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  start_at       TIMESTAMPTZ(3) NULL,
  end_at         TIMESTAMPTZ(3) NULL,
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_ad_campaign_status CHECK (status IN ('ACTIVE','PAUSED','ENDED'))
);


/* =========================================================
 * 27) ad_click_event
 * ========================================================= */
CREATE TABLE IF NOT EXISTS ad_click_event (
  click_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id   BIGINT NOT NULL REFERENCES ad_campaign(campaign_id),
  member_id     BIGINT NULL REFERENCES member(member_id),
  click_key     VARCHAR(120) NOT NULL,
  ledger_id     BIGINT NULL REFERENCES wallet_ledger(ledger_id),
  occurred_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_ad_click_key UNIQUE (click_key)
);


/* =========================================================
 * 28) inquiry
 * ========================================================= */
CREATE TABLE IF NOT EXISTS inquiry (
  inquiry_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id        BIGINT NOT NULL REFERENCES member(member_id),
  title            VARCHAR(200) NOT NULL,
  status           VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  answered_at      TIMESTAMPTZ(3) NULL,
  retention_until  TIMESTAMPTZ(3) NULL,
  created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_inquiry_status CHECK (status IN ('OPEN','ANSWERED','CLOSED'))
);


/* =========================================================
 * 29) inquiry_message
 * ========================================================= */
CREATE TABLE IF NOT EXISTS inquiry_message (
  message_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inquiry_id           BIGINT NOT NULL REFERENCES inquiry(inquiry_id),
  author_type          VARCHAR(20) NOT NULL,
  admin_member_id      BIGINT NULL REFERENCES member(member_id),
  body                 TEXT NOT NULL,
  created_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_inquiry_author_type CHECK (author_type IN ('CUSTOMER','ADMIN'))
);


/* =========================================================
 * 30) notice
 * ========================================================= */
CREATE TABLE IF NOT EXISTS notice (
  notice_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title          VARCHAR(200) NOT NULL,
  body           TEXT NOT NULL,
  is_public      BOOLEAN NOT NULL DEFAULT TRUE,
  notice_type    VARCHAR(30) NOT NULL DEFAULT 'OPS',
  status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  purge_after    TIMESTAMPTZ(3) NULL,
  created_by     BIGINT NULL REFERENCES member(member_id),
  updated_by     BIGINT NULL REFERENCES member(member_id),
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at     TIMESTAMPTZ(3) NULL,

  CONSTRAINT ck_notice_type CHECK (notice_type IN ('OPS','POLICY','PRIVACY','TERMS')),
  CONSTRAINT ck_notice_status CHECK (status IN ('ACTIVE','PENDING_DELETE','DELETED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_notice_active_policy_per_type
  ON notice(notice_type)
  WHERE deleted_at IS NULL
    AND status = 'ACTIVE'
    AND notice_type IN ('TERMS','PRIVACY','POLICY');

CREATE INDEX IF NOT EXISTS idx_notice_type_status_created
  ON notice(notice_type, status, created_at DESC);


/* =========================================================
 * 31) notice_attachment
 * ========================================================= */
CREATE TABLE IF NOT EXISTS notice_attachment (
  attachment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id      BIGINT NOT NULL REFERENCES notice(notice_id),
  file_url       TEXT NOT NULL,
  file_name      VARCHAR(200) NOT NULL,
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);


/* =========================================================
 * 32) notice_delivery
 * ========================================================= */
CREATE TABLE IF NOT EXISTS notice_delivery (
  delivery_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id     BIGINT NOT NULL REFERENCES notice(notice_id),
  member_id     BIGINT NOT NULL REFERENCES member(member_id),
  channel       VARCHAR(20) NOT NULL,
  status        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  sent_at       TIMESTAMPTZ(3) NULL,
  fail_reason   VARCHAR(200) NULL,
  created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_notice_delivery_channel CHECK (channel IN ('EMAIL','SMS','LMS','PUSH')),
  CONSTRAINT ck_notice_delivery_status CHECK (status IN ('PENDING','SENT','FAILED'))
);


/* =========================================================
 * ✅ member -> notice FK (순환 참조 방지 위해 별도 추가)
 * DO 블록을 사용하여 이미 존재하는지 체크 후 추가
 * ========================================================= */
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_member_terms_notice') THEN
        ALTER TABLE member ADD CONSTRAINT fk_member_terms_notice
            FOREIGN KEY (terms_notice_id) REFERENCES notice(notice_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_member_privacy_notice') THEN
        ALTER TABLE member ADD CONSTRAINT fk_member_privacy_notice
            FOREIGN KEY (privacy_notice_id) REFERENCES notice(notice_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_member_policy_notice') THEN
        ALTER TABLE member ADD CONSTRAINT fk_member_policy_notice
            FOREIGN KEY (policy_notice_id) REFERENCES notice(notice_id);
    END IF;
END $$;


/* =========================================================
 * 33) faq
 * ========================================================= */
CREATE TABLE IF NOT EXISTS faq (
  faq_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question    TEXT NOT NULL,
  answer      TEXT NOT NULL,
  locked      BOOLEAN NOT NULL DEFAULT TRUE,
  is_public   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ(3) NULL
);


/* =========================================================
 * 34) report
 * ========================================================= */
CREATE TABLE IF NOT EXISTS report (
  report_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_member_id  BIGINT NOT NULL REFERENCES member(member_id),
  target_type         VARCHAR(20) NOT NULL,
  target_job_id       BIGINT NULL REFERENCES job_posting(job_id),
  target_member_id   BIGINT NULL,
  reason_code         VARCHAR(30) NOT NULL,
  reason_detail       TEXT NULL,
  status              VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_report_target_type CHECK (target_type IN ('JOB_POSTING','MEMBER','ETC')),
  CONSTRAINT ck_report_status CHECK (status IN ('OPEN','ACCEPTED','REJECTED'))
);


ALTER TABLE report ADD COLUMN IF NOT EXISTS target_member_id BIGINT;

/* =========================================================
 * 35) moderation_action
 * ========================================================= */
CREATE TABLE IF NOT EXISTS moderation_action (
  action_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id        BIGINT NOT NULL REFERENCES report(report_id),
  admin_member_id  BIGINT NULL REFERENCES member(member_id),
  decision         VARCHAR(20) NOT NULL,
  sanction_level   INT NULL,
  restrict_days    INT NULL,
  reason           TEXT NOT NULL,
  decided_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_moderation_action_report UNIQUE (report_id),
  CONSTRAINT ck_moderation_decision CHECK (decision IN ('ACCEPT','REJECT'))
);


/* =========================================================
 * 36) member_penalty_point
 * ========================================================= */
CREATE TABLE IF NOT EXISTS member_penalty_point (
  penalty_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id    BIGINT NOT NULL REFERENCES member(member_id),
  report_id    BIGINT NULL REFERENCES report(report_id),
  points       INT NOT NULL,
  reason       VARCHAR(200) NOT NULL,
  created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);


/* =========================================================
 * 37) notification_template
 * ========================================================= */
CREATE TABLE IF NOT EXISTS notification_template (
  template_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_code  VARCHAR(50) NOT NULL,
  channel        VARCHAR(20) NOT NULL,
  subject        VARCHAR(200) NULL,
  body           TEXT NOT NULL,
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_notification_template_code UNIQUE (template_code),
  CONSTRAINT ck_notification_channel CHECK (channel IN ('EMAIL','SMS','PUSH'))
);


/* =========================================================
 * 38) notification_delivery
 * ========================================================= */
CREATE TABLE IF NOT EXISTS notification_delivery (
  delivery_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id   BIGINT NULL REFERENCES notification_template(template_id),
  member_id     BIGINT NOT NULL REFERENCES member(member_id),
  event_type    VARCHAR(40) NOT NULL,
  channel       VARCHAR(20) NOT NULL,
  status        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  sent_at       TIMESTAMPTZ(3) NULL,
  payload       JSONB NULL,
  is_read       BOOLEAN NOT NULL DEFAULT false,
  created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_notification_delivery_status CHECK (status IN ('PENDING','SENT','FAILED')),
  CONSTRAINT ck_notification_delivery_channel CHECK (channel IN ('EMAIL','SMS','PUSH'))
);


/* =========================================================
 * 39) outbox_event
 * ========================================================= */
CREATE TABLE IF NOT EXISTS outbox_event (
  outbox_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type      VARCHAR(50) NOT NULL,
  aggregate_type  VARCHAR(30) NOT NULL,
  aggregate_id    BIGINT NOT NULL,
  payload         JSONB NOT NULL,
  status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  retry_count     INT NOT NULL DEFAULT 0,
  next_run_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  locked_at       TIMESTAMPTZ(3) NULL,
  locked_by       VARCHAR(80) NULL,
  last_error      TEXT NULL,
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  processed_at    TIMESTAMPTZ(3) NULL,

  CONSTRAINT ck_outbox_status CHECK (status IN ('PENDING','PROCESSING','SUCCEEDED','FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_outbox_pick
  ON outbox_event(status, next_run_at, outbox_id);

CREATE INDEX IF NOT EXISTS idx_outbox_agg
  ON outbox_event(aggregate_type, aggregate_id);


/* =========================================================
 * A) wallet_credit_lot
 * ========================================================= */
CREATE TABLE IF NOT EXISTS wallet_credit_lot (
  lot_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id           BIGINT NOT NULL REFERENCES wallet(wallet_id),
  payment_id          BIGINT NOT NULL REFERENCES payment(payment_id),
  granted_credit      INT NOT NULL,
  remaining_credit    INT NOT NULL,
  unit_price_amount   NUMERIC(12,2) NOT NULL,
  currency            CHAR(3) NOT NULL DEFAULT 'KRW',
  pricing_meta        JSONB NULL,
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_wallet_credit_lot_credit
    CHECK (
      granted_credit >= 0
      AND remaining_credit >= 0
      AND remaining_credit <= granted_credit
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_wallet_credit_lot_wallet_payment
  ON wallet_credit_lot(wallet_id, payment_id);

CREATE INDEX IF NOT EXISTS idx_wallet_credit_lot_wallet_created
  ON wallet_credit_lot(wallet_id, created_at ASC);


/* =========================================================
 * B) payment_cancel
 * ========================================================= */
CREATE TABLE IF NOT EXISTS payment_cancel (
  cancel_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id             BIGINT NOT NULL REFERENCES payment(payment_id),
  toss_transaction_key   VARCHAR(80) NOT NULL,
  cancel_status          VARCHAR(40) NULL,
  cancel_amount          NUMERIC(12,2) NOT NULL,
  cancel_reason          VARCHAR(200) NOT NULL,
  canceled_at            TIMESTAMPTZ(3) NULL,
  idempotency_key        VARCHAR(100) NOT NULL,
  raw_cancel             JSONB NULL,
  created_at             TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_payment_cancel_tx UNIQUE (payment_id, toss_transaction_key),
  CONSTRAINT uq_payment_cancel_idem UNIQUE (idempotency_key),
  CONSTRAINT ck_payment_cancel_amount CHECK (cancel_amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_payment_cancel_payment_created
  ON payment_cancel(payment_id, created_at DESC);


/* =========================================================
 * updated_at 자동 갱신 트리거 적용 (안전하게 스킵 처리)
 * DO 블록을 통해 트리거 존재 여부를 확인하고 생성
 * ========================================================= */
DO $$
DECLARE
    t text;
BEGIN
    -- 트리거를 적용할 테이블 목록
    FOR t IN SELECT unnest(ARRAY[
        'member', 'employer', 'product', 'orders', 'payment', 'wallet',
        'subscription', 'job_posting', 'resume', 'job_application',
        'interview_schedule', 'resume_project', 'resume_career',
        'resume_certificate', 'inquiry', 'notice', 'faq', 'ad_campaign',
        'outbox_event', 'wallet_credit_lot',
        'phone_verification', 'member_login_log', 'employer_member',
        'subscription_billing_cycle', 'interview_response', 'resume_profile',
        'resume_attachment', 'resume_link', 'job_scrap', 'job_view_log',
        'ad_click_event', 'inquiry_message', 'notice_attachment',
        'notice_delivery', 'report', 'moderation_action', 'member_penalty_point',
        'notification_template', 'payment_cancel'
    ])
    LOOP
        -- 트리거가 이미 존재하는지 확인 (트리거 이름: trg_set_updated_at_테이블명)
        IF NOT EXISTS (
            SELECT 1 FROM pg_trigger
            WHERE tgname = 'trg_set_updated_at_' || t
        ) THEN
            -- 동적 SQL로 트리거 생성
            EXECUTE format('
                CREATE TRIGGER trg_set_updated_at_%I
                BEFORE UPDATE ON %I
                FOR EACH ROW EXECUTE FUNCTION set_updated_at()', t, t);
        END IF;
    END LOOP;
END $$;


-- =================================================================
-- (참고) AUTO-GENERATED POSTGRESQL DDL 섹션 처리
-- 이미 위에서 IF NOT EXISTS로 상세하게 정의했으므로,
-- 아래 스크립트는 실행되어도 기존 테이블이 있으면 무시됩니다.
-- =================================================================

CREATE TABLE IF NOT EXISTS member (
    member_id BIGSERIAL PRIMARY KEY,
    member_uid UUID NOT NULL UNIQUE,
    email VARCHAR(320) NOT NULL UNIQUE,
    login_id VARCHAR(50),
    password_hash VARCHAR(255),
    auth_provider VARCHAR(20) NOT NULL,
    name VARCHAR(80) NOT NULL,
    gender VARCHAR(20),
    birth_date VARCHAR(20),
    phone VARCHAR(20),
    phone_verified_at TIMESTAMPTZ,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    last_login_at TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ,
    failed_login_count INT NOT NULL,
    locked_until TIMESTAMPTZ,
    terms_notice_id BIGINT,
    terms_agreed_at TIMESTAMPTZ,
    privacy_notice_id BIGINT,
    privacy_agreed_at TIMESTAMPTZ,
    policy_notice_id BIGINT,
    policy_agreed_at TIMESTAMPTZ,
    marketing_opt_in BOOLEAN NOT NULL,
    marketing_agreed_at TIMESTAMPTZ,
    consent_ip VARCHAR(45),
    consent_user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS employer (
    employer_id BIGSERIAL PRIMARY KEY,
    employer_uid UUID NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    logo_url TEXT,
    industry VARCHAR(80),
    founded_year INT,
    employee_count INT,
    location VARCHAR(120),
    description TEXT,
    culture TEXT,
    benefits TEXT,
    tech_stack TEXT,
    contact_email VARCHAR(320),
    contact_phone VARCHAR(20),
    website_url TEXT,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product (
    product_id BIGSERIAL PRIMARY KEY,
    product_code VARCHAR(100) NOT NULL UNIQUE,
    name TEXT NOT NULL,
    sale_status VARCHAR(30) NOT NULL,
    price_amount NUMERIC(19,4),
    currency VARCHAR(10),
    product_type VARCHAR(30),
    credit_amount INT,
    plan_tier VARCHAR(20),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    order_id BIGSERIAL PRIMARY KEY,
    order_uid UUID NOT NULL,
    buyer_type VARCHAR(20) NOT NULL,
    buyer_member_id BIGINT REFERENCES member(member_id),
    buyer_employer_id BIGINT REFERENCES employer(employer_id),
    product_id BIGINT REFERENCES product(product_id),
    order_amount NUMERIC(19,4) NOT NULL,
    currency VARCHAR(10),
    status VARCHAR(30),
    idempotency_key VARCHAR(100),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

BEGIN;

-- 1) (필수) trigram 인덱스/유사도 검색용 확장
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2) alias -> canonical 매핑 테이블
CREATE TABLE IF NOT EXISTS stack_alias (
  alias        text PRIMARY KEY,           -- 사용자가 입력/공고에 등장할 수 있는 표현(정규화 전)
  canonical    text NOT NULL,              -- 내부 표준 키(예: 'java', 'spring boot')
  display_name text,                       -- 출력 표기(예: 'JAVA', 'Spring Boot') - 선택
  is_active    boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

-- 3) updated_at 자동 갱신(선택)
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_stack_alias_updated_at ON stack_alias;
CREATE TRIGGER trg_stack_alias_updated_at
BEFORE UPDATE ON stack_alias
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;

SELECT
  conname,
  conrelid::regclass AS fk_table,
  pg_get_constraintdef(oid) AS def
FROM pg_constraint
WHERE contype = 'f'
  AND confrelid = 'public.stack_alias'::regclass;

-----
CREATE EXTENSION IF NOT EXISTS pg_trgm;

------
DROP TRIGGER IF EXISTS trg_stack_alias_updated_at ON public.stack_alias;
DROP FUNCTION IF EXISTS public.stack_alias_set_updated_at();

-----
DROP INDEX IF EXISTS public.ix_stack_alias_alias_trgm;
DROP INDEX IF EXISTS public.ix_stack_alias_canonical_trgm;

-- 혹시 예전에 만들었던 다른 이름의 인덱스가 있으면 추가로 여기에 DROP INDEX IF EXISTS ...

-----
ALTER TABLE public.stack_alias
  DROP CONSTRAINT IF EXISTS ux_stack_alias_alias;

-----
ALTER TABLE public.stack_alias
  ADD COLUMN IF NOT EXISTS entity_type text NOT NULL DEFAULT 'STACK';

-- 혹시 과거에 NULL이 들어간 row가 있었다면 대비
UPDATE public.stack_alias
SET entity_type = 'STACK'
WHERE entity_type IS NULL;

-----
ALTER TABLE public.stack_alias
  DROP CONSTRAINT IF EXISTS stack_alias_entity_type_chk;

ALTER TABLE public.stack_alias
  ADD CONSTRAINT stack_alias_entity_type_chk
  CHECK (entity_type IN ('STACK','INDUSTRY'));

-----
ALTER TABLE public.stack_alias
  DROP CONSTRAINT IF EXISTS stack_alias_pkey;

ALTER TABLE public.stack_alias
  ADD CONSTRAINT stack_alias_pkey PRIMARY KEY (entity_type, alias);

COMMIT;

-----
CREATE INDEX IF NOT EXISTS ix_stack_alias_alias_trgm_stack
  ON public.stack_alias USING gin (alias gin_trgm_ops)
  WHERE is_active AND entity_type='STACK';

CREATE INDEX IF NOT EXISTS ix_stack_alias_alias_trgm_industry
  ON public.stack_alias USING gin (alias gin_trgm_ops)
  WHERE is_active AND entity_type='INDUSTRY';

CREATE INDEX IF NOT EXISTS ix_stack_alias_canonical_trgm_stack
  ON public.stack_alias USING gin (canonical gin_trgm_ops)
  WHERE is_active AND entity_type='STACK';

CREATE INDEX IF NOT EXISTS ix_stack_alias_canonical_trgm_industry
  ON public.stack_alias USING gin (canonical gin_trgm_ops)
  WHERE is_active AND entity_type='INDUSTRY';

-----
CREATE OR REPLACE FUNCTION public.stack_alias_set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_stack_alias_updated_at
BEFORE UPDATE ON public.stack_alias
FOR EACH ROW EXECUTE FUNCTION public.stack_alias_set_updated_at();

-----
DROP MATERIALIZED VIEW IF EXISTS public.stack_vocab;

CREATE MATERIALIZED VIEW public.stack_vocab AS
WITH tokens AS (
  SELECT
    lower(regexp_replace(btrim(tok), E'\s+', ' ', 'g')) AS token
  FROM public.job_posting jp
  CROSS JOIN LATERAL unnest(coalesce(jp.stack, ARRAY[]::text[])) AS s(item)
  CROSS JOIN LATERAL regexp_split_to_table(coalesce(s.item, ''), E'\s[,/|]+\s') AS tok
  WHERE jp.deleted_at IS NULL
    AND jp.status = 'OPEN'
    AND jp.stack IS NOT NULL
)
SELECT token, COUNT(*)::bigint AS cnt
FROM tokens
WHERE token <> ''
  AND length(token) BETWEEN 2 AND 40
  AND token !~ '^[0-9]+$'
  AND token ~ '[a-zA-Z가-힣]'
GROUP BY token
WITH NO DATA;

-- 인덱스
CREATE UNIQUE INDEX IF NOT EXISTS ux_stack_vocab_token ON public.stack_vocab(token);

CREATE INDEX IF NOT EXISTS ix_stack_vocab_token_trgm
  ON public.stack_vocab USING GIN (token gin_trgm_ops);

-- 데이터 채우기
REFRESH MATERIALIZED VIEW public.stack_vocab;

-----
-- node 계열은 nodejs로
INSERT INTO public.stack_alias(entity_type, alias, canonical, display_name)
VALUES
  ('STACK','node','nodejs','Node.js'),
  ('STACK','node.js','nodejs','Node.js'),
  ('STACK','nodejs','nodejs','Node.js')
ON CONFLICT (entity_type, alias) DO UPDATE
SET canonical=EXCLUDED.canonical,
    display_name=EXCLUDED.display_name,
    is_active=true,
    updated_at=now();

-- vue 계열은 vuejs로
INSERT INTO public.stack_alias(entity_type, alias, canonical, display_name)
VALUES
  ('STACK','vue','vuejs','Vue.js'),
  ('STACK','vue.js','vuejs','Vue.js'),
  ('STACK','vuejs','vuejs','Vue.js')
ON CONFLICT (entity_type, alias) DO UPDATE
SET canonical=EXCLUDED.canonical,
    display_name=EXCLUDED.display_name,
    is_active=true,
    updated_at=now();

-- next 계열은 nextjs로
INSERT INTO public.stack_alias(entity_type, alias, canonical, display_name)
VALUES
  ('STACK','next','nextjs','Next.js'),
  ('STACK','next.js','nextjs','Next.js'),
  ('STACK','nextjs','nextjs','Next.js')
ON CONFLICT (entity_type, alias) DO UPDATE
SET canonical=EXCLUDED.canonical,
    display_name=EXCLUDED.display_name,
    is_active=true,
    updated_at=now();

-----
-----

-- AI/Machine Learning
INSERT INTO public.stack_alias(entity_type, alias, canonical, display_name) VALUES
('INDUSTRY','ai','ai/machine learning','AI/Machine Learning'),
('INDUSTRY','ml','ai/machine learning','AI/Machine Learning'),
('INDUSTRY','인공지능','ai/machine learning','AI/Machine Learning'),
('INDUSTRY','머신러닝','ai/machine learning','AI/Machine Learning'),
('INDUSTRY','딥러닝','ai/machine learning','AI/Machine Learning'),
('INDUSTRY','llm','ai/machine learning','AI/Machine Learning')
ON CONFLICT (entity_type, alias) DO UPDATE
SET canonical=EXCLUDED.canonical, display_name=EXCLUDED.display_name, is_active=true, updated_at=now();

-- Blockchain/Crypto
INSERT INTO public.stack_alias(entity_type, alias, canonical, display_name) VALUES
('INDUSTRY','blockchain','blockchain/crypto','Blockchain/Crypto'),
('INDUSTRY','crypto','blockchain/crypto','Blockchain/Crypto'),
('INDUSTRY','블록체인','blockchain/crypto','Blockchain/Crypto'),
('INDUSTRY','가상자산','blockchain/crypto','Blockchain/Crypto'),
('INDUSTRY','암호화폐','blockchain/crypto','Blockchain/Crypto')
ON CONFLICT (entity_type, alias) DO UPDATE
SET canonical=EXCLUDED.canonical, display_name=EXCLUDED.display_name, is_active=true, updated_at=now();

-- Cloud/Infrastructure
INSERT INTO public.stack_alias(entity_type, alias, canonical, display_name) VALUES
('INDUSTRY','cloud','cloud/infrastructure','Cloud/Infrastructure'),
('INDUSTRY','infra','cloud/infrastructure','Cloud/Infrastructure'),
('INDUSTRY','infrastructure','cloud/infrastructure','Cloud/Infrastructure'),
('INDUSTRY','클라우드','cloud/infrastructure','Cloud/Infrastructure'),
('INDUSTRY','인프라','cloud/infrastructure','Cloud/Infrastructure')
ON CONFLICT (entity_type, alias) DO UPDATE
SET canonical=EXCLUDED.canonical, display_name=EXCLUDED.display_name, is_active=true, updated_at=now();

-- Data Analytics
INSERT INTO public.stack_alias(entity_type, alias, canonical, display_name) VALUES
('INDUSTRY','data','data analytics','Data Analytics'),
('INDUSTRY','analytics','data analytics','Data Analytics'),
('INDUSTRY','bi','data analytics','Data Analytics'),
('INDUSTRY','데이터','data analytics','Data Analytics'),
('INDUSTRY','데이터분석','data analytics','Data Analytics')
ON CONFLICT (entity_type, alias) DO UPDATE
SET canonical=EXCLUDED.canonical, display_name=EXCLUDED.display_name, is_active=true, updated_at=now();

-- E-commerce
INSERT INTO public.stack_alias(entity_type, alias, canonical, display_name) VALUES
('INDUSTRY','ecommerce','e-commerce','E-commerce'),
('INDUSTRY','e-commerce','e-commerce','E-commerce'),
('INDUSTRY','커머스','e-commerce','E-commerce'),
('INDUSTRY','이커머스','e-commerce','E-commerce'),
('INDUSTRY','쇼핑몰','e-commerce','E-commerce')
ON CONFLICT (entity_type, alias) DO UPDATE
SET canonical=EXCLUDED.canonical, display_name=EXCLUDED.display_name, is_active=true, updated_at=now();

-- Enterprise Software
INSERT INTO public.stack_alias(entity_type, alias, canonical, display_name) VALUES
('INDUSTRY','enterprise','enterprise software','Enterprise Software'),
('INDUSTRY','b2b','enterprise software','Enterprise Software'),
('INDUSTRY','erp','enterprise software','Enterprise Software'),
('INDUSTRY','기업용','enterprise software','Enterprise Software'),
('INDUSTRY','엔터프라이즈','enterprise software','Enterprise Software')
ON CONFLICT (entity_type, alias) DO UPDATE
SET canonical=EXCLUDED.canonical, display_name=EXCLUDED.display_name, is_active=true, updated_at=now();

-- Fintech
INSERT INTO public.stack_alias(entity_type, alias, canonical, display_name) VALUES
('INDUSTRY','fintech','fintech','Fintech'),
('INDUSTRY','핀테크','fintech','Fintech'),
('INDUSTRY','금융it','fintech','Fintech'),
('INDUSTRY','금융','fintech','Fintech')
ON CONFLICT (entity_type, alias) DO UPDATE
SET canonical=EXCLUDED.canonical, display_name=EXCLUDED.display_name, is_active=true, updated_at=now();

-- Gaming
INSERT INTO public.stack_alias(entity_type, alias, canonical, display_name) VALUES
('INDUSTRY','game','gaming','Gaming'),
('INDUSTRY','gaming','gaming','Gaming'),
('INDUSTRY','게임','gaming','Gaming')
ON CONFLICT (entity_type, alias) DO UPDATE
SET canonical=EXCLUDED.canonical, display_name=EXCLUDED.display_name, is_active=true, updated_at=now();

-- IT/Web Service
INSERT INTO public.stack_alias(entity_type, alias, canonical, display_name) VALUES
('INDUSTRY','it','it/web service','IT/Web Service'),
('INDUSTRY','web','it/web service','IT/Web Service'),
('INDUSTRY','web service','it/web service','IT/Web Service'),
('INDUSTRY','웹서비스','it/web service','IT/Web Service'),
('INDUSTRY','it서비스','it/web service','IT/Web Service')
ON CONFLICT (entity_type, alias) DO UPDATE
SET canonical=EXCLUDED.canonical, display_name=EXCLUDED.display_name, is_active=true, updated_at=now();

-- Mobile Platform
INSERT INTO public.stack_alias(entity_type, alias, canonical, display_name) VALUES
('INDUSTRY','mobile','mobile platform','Mobile Platform'),
('INDUSTRY','android','mobile platform','Mobile Platform'),
('INDUSTRY','ios','mobile platform','Mobile Platform'),
('INDUSTRY','모바일','mobile platform','Mobile Platform'),
('INDUSTRY','모바일플랫폼','mobile platform','Mobile Platform')
ON CONFLICT (entity_type, alias) DO UPDATE
SET canonical=EXCLUDED.canonical, display_name=EXCLUDED.display_name, is_active=true, updated_at=now();

SELECT conname, contype, pg_get_constraintdef(oid) AS def
FROM pg_constraint
WHERE conrelid = 'public.stack_alias'::regclass
ORDER BY contype, conname;

-----
SELECT entity_type, canonical, COUNT(*) AS n
FROM public.stack_alias
WHERE is_active
GROUP BY entity_type, canonical
ORDER BY entity_type, canonical;

-----
-- 값 목록
SELECT DISTINCT e.industry
FROM public.job_posting jp
JOIN public.employer e ON e.employer_id = jp.employer_id
WHERE jp.deleted_at IS NULL
  AND jp.status = 'OPEN'
  AND e.industry IS NOT NULL
ORDER BY e.industry;

-- 산업별 공고 수
SELECT e.industry, COUNT(*)::bigint AS cnt
FROM public.job_posting jp
JOIN public.employer e ON e.employer_id = jp.employer_id
WHERE jp.deleted_at IS NULL
  AND jp.status = 'OPEN'
  AND e.industry IS NOT NULL
GROUP BY e.industry
ORDER BY cnt DESC, e.industry ASC;

-----

/* =========================================================
 * 1. subscription (구독) 테이블 컬럼 추가 및 외래 키 설정
 * 이미 존재할 경우 스킵하도록 DO 블록 사용
 * ========================================================= */
DO $$
BEGIN
    -- 카드사 정보 컬럼 추가
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name='subscription' AND column_name='card_company') THEN
        ALTER TABLE subscription ADD COLUMN card_company VARCHAR(255);
    END IF;

    -- 카드 번호 컬럼 추가
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name='subscription' AND column_name='card_number') THEN
        ALTER TABLE subscription ADD COLUMN card_number VARCHAR(255);
    END IF;

    -- 다음 상품 ID (변경용) 컬럼 추가
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name='subscription' AND column_name='next_product_id') THEN
        ALTER TABLE subscription ADD COLUMN next_product_id BIGINT;
    END IF;

    -- next_product_id에 대한 외래 키 제약 조건 추가 (product 테이블 참조)
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'fk_subscription_next_product') THEN
        ALTER TABLE subscription
        ADD CONSTRAINT fk_subscription_next_product
        FOREIGN KEY (next_product_id) REFERENCES product (product_id);
    END IF;
END $$;


/* =========================================================
 * 2. stack_vocab 구체화된 뷰 (최신 로직 반영)
 * 기존 뷰를 삭제하고 제공된 로직으로 재생성합니다.
 * ========================================================= */
DROP MATERIALIZED VIEW IF EXISTS public.stack_vocab;

CREATE MATERIALIZED VIEW public.stack_vocab AS
WITH tokens AS (
  SELECT
    lower(regexp_replace(btrim(tok), E'\\s+', ' ', 'g')) AS token
  FROM public.job_posting jp
  CROSS JOIN LATERAL unnest(coalesce(jp.stack, ARRAY[]::text[])) AS s(item)
  CROSS JOIN LATERAL regexp_split_to_table(coalesce(s.item, ''), E'\\s[,/|]+\\s') AS tok
  WHERE jp.deleted_at IS NULL
    AND jp.status = 'OPEN'
    AND jp.stack IS NOT NULL
)
SELECT token, COUNT(*)::bigint AS cnt
FROM tokens
WHERE token <> ''
  AND length(token) BETWEEN 2 AND 40
  AND token !~ '^[0-9]+$'
  AND token ~ '[a-zA-Z가-힣]'
GROUP BY token
WITH NO DATA;

-- 인덱스 및 데이터 채우기 (이미 존재 시 스킵)
CREATE UNIQUE INDEX IF NOT EXISTS ux_stack_vocab_token ON public.stack_vocab(token);
CREATE INDEX IF NOT EXISTS ix_stack_vocab_token_trgm ON public.stack_vocab USING GIN (token gin_trgm_ops);
REFRESH MATERIALIZED VIEW public.stack_vocab;


/* =========================================================
 * 3. 정보 확인 및 기타 설정
 * ========================================================= */
-- job_posting 테이블의 salary_text 컬럼 정보 확인 (조회용)
SELECT table_name, column_name, data_type, character_maximum_length
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'job_posting'
  AND column_name = 'salary_text';

-- pg_trgm 확장 설치
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- stack_alias 테이블의 display_name 이후 필드 타입 및 기본값 재설정 (필요 시)
-- 이미 테이블이 존재하므로 부족한 속성이 있다면 ALTER TABLE로 보완하세요.


-- 0) 확장
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 1) 기존 있으면 삭제(제약/인덱스 포함)
DROP MATERIALIZED VIEW IF EXISTS public.industry_vocab;
DROP TABLE IF EXISTS public.industry_alias CASCADE;

-- 2) 업종 alias 테이블
CREATE TABLE public.industry_alias (
  alias        text PRIMARY KEY,
  canonical    text NOT NULL,
  display_name text NULL,
  is_active    boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

-- 3) 검색 성능(선택)
CREATE INDEX IF NOT EXISTS ix_industry_alias_alias_trgm
ON public.industry_alias USING gin (alias gin_trgm_ops)
WHERE is_active;

CREATE INDEX IF NOT EXISTS ix_industry_alias_canonical_trgm
ON public.industry_alias USING gin (canonical gin_trgm_ops)
WHERE is_active;

-- 4) vocab (fuzzy 후보용) - alias/canonical 둘 다 토큰화
CREATE MATERIALIZED VIEW public.industry_vocab AS
WITH tokens AS (
  SELECT lower(btrim(tok)) AS token
  FROM public.industry_alias ia
  CROSS JOIN LATERAL regexp_split_to_table(
    coalesce(ia.alias,'') || ',' ||
 coalesce(ia.canonical,''),
    '\s[,/|]+\s'
  ) AS tok
  WHERE ia.is_active
)
SELECT token, COUNT(*)::bigint AS cnt
FROM tokens
WHERE token <> ''
GROUP BY token;

CREATE UNIQUE INDEX IF NOT EXISTS ux_industry_vocab_token
ON public.industry_vocab (token);

CREATE INDEX IF NOT EXISTS ix_industry_vocab_token_trgm
ON public.industry_vocab USING gin (token gin_trgm_ops);

-- 5) 초기 데이터 예시(원하는 만큼 추가)
INSERT INTO public.industry_alias(alias, canonical, display_name) VALUES
('it', 'it', 'IT'),
('it서비스', 'it', 'IT'),
('웹서비스', 'it', 'IT'),
('ai', 'ai', 'AI'),
('인공지능', 'ai', 'AI'),
('데이터', 'data', 'Data'),
('데이터서비스', 'data', 'Data'),
('mobile', 'mobile', 'Mobile'),
('모바일', 'mobile', 'Mobile')
ON CONFLICT (alias) DO UPDATE SET
  canonical = EXCLUDED.canonical,
  display_name = EXCLUDED.display_name,
  is_active = true,
  updated_at = now();

-- 6) 변경 후 refresh(데이터 추가/수정할 때마다)
REFRESH MATERIALIZED VIEW public.industry_vocab;

