-- PostgreSQL DDL (요구사항 반영 + "정책 동의" 테이블 추가 없이 처리)
-- ✅ 정책 동의 방식:
--   - notice 테이블을 "공지(OPS) + 정책문서(TERMS/PRIVACY/POLICY)" 저장소로 재사용
--   - member 테이블에 "동의한 notice_id + 동의 시각(+ ip/ua)"만 컬럼으로 보관
--   - member -> notice FK는 notice 생성 이후 ALTER TABLE로 추가(순환 참조 방지)
--
-- ✅ 이번 반영 핵심:
--   - job_posting.ad_bid_credit: "광고 아님=0" 정규화 (DEFAULT 0 + NOT NULL + CHECK >=0)
--   - job_posting 광고 프리필터링 부분 인덱스 추가 (status=OPEN, ad_bid_credit>0)
--   - resume.summary_status: DEFAULT/CK 불일치 수정 (NONE 포함)
--   - resume.emploment_type 오탈자 수정 -> employment_type
--   - updated_at 자동 갱신 트리거 전략 추가
--
-- =========================================================
-- Extensions
-- =========================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS vector;    -- pgvector
-- =========================================================
-- updated_at 자동 갱신 전략 (트리거)
-- =========================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


/* =========================================================
 * 1) member (회원 기본 + 보안 상태)  ✅ login_id + 정책동의 컬럼
 *    ✅ phone NULL 허용 (소셜 사용자 추후 연결)
 *    ✅ gender / birth_date 추가 (나이는 birth_date로 계산)
 * ========================================================= */
CREATE TABLE member (
  member_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_uid              UUID NOT NULL,                 -- 앱 생성(UUID)
  email                   VARCHAR(320) NOT NULL,
  login_id                VARCHAR(50) NULL,              -- 소셜은 NULL 허용
  auth_provider           VARCHAR(20) NOT NULL DEFAULT 'OTHER', -- NAVER/GOOGLE/KAKAO/OTHER
  password_hash           VARCHAR(255) NULL,             -- 소셜 전용이면 NULL

  name                    VARCHAR(80) NOT NULL,

  -- ✅ A안: 개인정보는 member가 원천
  gender                  VARCHAR(20) NULL,              -- MALE/FEMALE
  birth_date              DATE NULL,                     -- 나이는 birth_date로 계산

  phone                   VARCHAR(20) NULL,              -- ✅ NULL 허용(소셜 사용자 추후 연결)
  role                    VARCHAR(20) NOT NULL,
  status                  VARCHAR(20) NOT NULL,

  last_login_at           TIMESTAMPTZ(3) NULL,
  password_changed_at     TIMESTAMPTZ(3) NULL,
  failed_login_count      INT NOT NULL DEFAULT 0,
  locked_until            TIMESTAMPTZ(3) NULL,

  -- ✅ 휴대폰 OTP 인증 완료 시각(점유 확인)
  phone_verified_at       TIMESTAMPTZ(3) NULL,

  created_at              TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at              TIMESTAMPTZ(3) NULL,

  -- ✅ 정책 동의(테이블 추가 없이) : notice(notice_id) 참조 예정
  -- FK 제약은 notice 생성 이후 ALTER TABLE로 추가
  terms_notice_id         BIGINT NULL,
  terms_agreed_at         TIMESTAMPTZ(3) NULL,
  privacy_notice_id       BIGINT NULL,
  privacy_agreed_at       TIMESTAMPTZ(3) NULL,
  policy_notice_id        BIGINT NULL,
  policy_agreed_at        TIMESTAMPTZ(3) NULL,

  marketing_opt_in        BOOLEAN NOT NULL DEFAULT FALSE,
  marketing_agreed_at     TIMESTAMPTZ(3) NULL,

  consent_ip              VARCHAR(45) NULL,   -- IPv4/IPv6
  consent_user_agent      TEXT NULL,

  CONSTRAINT uq_member_uid UNIQUE (member_uid),
  CONSTRAINT uq_member_email UNIQUE (email),

  CONSTRAINT ck_member_role
    CHECK (role IN ('CANDIDATE','EMPLOYER','SERVICEADMIN','APPROVEADMIN','MASTER')),
  CONSTRAINT ck_member_status
    CHECK (status IN ('ACTIVE','SUSPENDED','WITHDRAWN')),
  CONSTRAINT ck_member_failed_login_count
    CHECK (failed_login_count >= 0),

  CONSTRAINT ck_member_auth_provider
    CHECK (auth_provider IN ('NAVER','GOOGLE','KAKAO','OTHER')),

  CONSTRAINT ck_member_gender
    CHECK (gender IS NULL OR gender IN ('MALE','FEMALE')),

  CONSTRAINT ck_member_phone_verified_requires_phone
    CHECK (phone_verified_at IS NULL OR phone IS NOT NULL),

  -- ✅ ACTIVE 상태는 필수 동의가 있어야 함(운영 정책에 맞게 조정 가능)
  CONSTRAINT ck_member_required_consents
    CHECK (
      status <> 'ACTIVE'
      OR (
        terms_notice_id   IS NOT NULL AND terms_agreed_at   IS NOT NULL AND
        privacy_notice_id IS NOT NULL AND privacy_agreed_at IS NOT NULL
      )
    ),

  CONSTRAINT ck_member_marketing_optin_time
    CHECK (
      marketing_opt_in IS FALSE
      OR (marketing_opt_in IS TRUE AND marketing_agreed_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_member_login_id_active
  ON member (login_id)
  WHERE deleted_at IS NULL AND login_id IS NOT NULL;

CREATE UNIQUE INDEX uq_member_phone_verified_active
  ON member (phone)
  WHERE deleted_at IS NULL
    AND phone IS NOT NULL
    AND phone_verified_at IS NOT NULL;


/* =========================================================
 * 1-1) phone_verification (휴대폰 OTP 인증)
 * ========================================================= */
CREATE TABLE phone_verification (
  verification_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  phone               VARCHAR(20) NOT NULL,
  purpose             VARCHAR(20) NOT NULL,      -- SIGNUP / PASSWORD_RESET / PHONE_LINK
  code_hash           CHAR(64) NOT NULL,         -- HMAC-SHA256 hex 등

  expires_at          TIMESTAMPTZ(3) NOT NULL,
  verified_at         TIMESTAMPTZ(3) NULL,
  consumed_at         TIMESTAMPTZ(3) NULL,

  attempt_count       INT NOT NULL DEFAULT 0,
  resend_count        INT NOT NULL DEFAULT 0,
  last_sent_at        TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  request_ip          VARCHAR(45) NULL,
  request_user_agent  TEXT NULL,

  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_phone_verification_purpose
    CHECK (purpose IN ('SIGNUP','PASSWORD_RESET','PHONE_LINK')),
  CONSTRAINT ck_phone_verification_attempt
    CHECK (attempt_count >= 0),
  CONSTRAINT ck_phone_verification_resend
    CHECK (resend_count >= 0),
  CONSTRAINT ck_phone_verification_phone_digits
    CHECK (phone ~ '^[0-9]{10,15}$')
);

CREATE INDEX idx_phone_verification_phone_purpose_created
  ON phone_verification(phone, purpose, created_at DESC);

CREATE INDEX idx_phone_verification_active
  ON phone_verification(phone, purpose, expires_at)
  WHERE consumed_at IS NULL;


/* =========================================================
 * 2) member_login_log (로그인 시도 로그)
 * ========================================================= */
CREATE TABLE member_login_log (
  login_log_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id       BIGINT NOT NULL REFERENCES member(member_id),
  success         BOOLEAN NOT NULL DEFAULT FALSE,
  ip_address      VARCHAR(45) NULL,
  user_agent      TEXT NULL,
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);

CREATE INDEX idx_member_login_log_member_created
  ON member_login_log(member_id, created_at DESC);


/* =========================================================
 * 3) employer (기업 프로필)
 * ========================================================= */
CREATE TABLE employer (
  employer_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_uid    UUID NOT NULL,
  name            VARCHAR(120) NOT NULL,
  logo_url        TEXT NULL,
  industry        VARCHAR(80) NULL,
  founded_year    INT NULL,
  employee_count  INT NULL,
  location        VARCHAR(120) NULL,
  description     TEXT NULL,
  culture         TEXT NULL,
  benefits        TEXT NULL,
  tech_stack      TEXT NULL,
  contact_email   VARCHAR(320) NULL,
  contact_phone   VARCHAR(20) NULL,
  website_url     TEXT NULL,
  status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at      TIMESTAMPTZ(3) NULL,

  CONSTRAINT uq_employer_uid UNIQUE (employer_uid),
  CONSTRAINT ck_employer_status CHECK (status IN ('ACTIVE','SUSPENDED','CLOSED'))
);

CREATE INDEX idx_employer_name ON employer(name);


/* =========================================================
 * 4) employer_member (기업-회원 소속 매핑)
 * ========================================================= */
CREATE TABLE employer_member (
  employer_member_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id          BIGINT NOT NULL REFERENCES employer(employer_id),
  member_id            BIGINT NOT NULL REFERENCES member(member_id),
  role_in_company      VARCHAR(20) NOT NULL,
  active               BOOLEAN NOT NULL DEFAULT TRUE,
  created_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_employer_member UNIQUE (employer_id, member_id),
  CONSTRAINT ck_role_in_company CHECK (role_in_company IN ('OWNER','HR','STAFF'))
);


/* =========================================================
 * 5) product (상품)
 * ========================================================= */
CREATE TABLE product (
  product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_code    VARCHAR(40) NOT NULL,
  product_type    VARCHAR(20) NOT NULL,
  name            VARCHAR(120) NOT NULL,
  sale_status     VARCHAR(20) NOT NULL,
  price_amount    NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  currency        CHAR(3) NOT NULL DEFAULT 'KRW',
  credit_amount   INT NULL,
  plan_tier       VARCHAR(20) NULL,
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at      TIMESTAMPTZ(3) NULL,

  CONSTRAINT uq_product_code UNIQUE (product_code),
  CONSTRAINT ck_product_type CHECK (product_type IN ('ONE_TIME','SUBSCRIPTION')),
  CONSTRAINT ck_sale_status CHECK (sale_status IN ('ON_SALE','PAUSED','STOPPED'))
);


/* =========================================================
 * 6) orders (주문)
 * ========================================================= */
CREATE TABLE orders (
  order_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_uid           UUID NOT NULL,
  buyer_type          VARCHAR(20) NOT NULL,
  buyer_member_id     BIGINT NULL REFERENCES member(member_id),
  buyer_employer_id   BIGINT NULL REFERENCES employer(employer_id),
  product_id          BIGINT NOT NULL REFERENCES product(product_id),
  order_amount        NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  status              VARCHAR(20) NOT NULL DEFAULT 'CREATED',
  idempotency_key     VARCHAR(64) NOT NULL,
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_order_uid UNIQUE (order_uid),
  CONSTRAINT uq_orders_idempotency UNIQUE (idempotency_key),
  CONSTRAINT ck_orders_buyer_type CHECK (buyer_type IN ('MEMBER','EMPLOYER')),
  CONSTRAINT ck_orders_status CHECK (status IN ('CREATED','PAID','CANCELED','FAILED')),
  CONSTRAINT ck_orders_buyer_fk
    CHECK (
      (buyer_type = 'MEMBER'   AND buyer_member_id IS NOT NULL AND buyer_employer_id IS NULL) OR
      (buyer_type = 'EMPLOYER' AND buyer_employer_id IS NOT NULL AND buyer_member_id IS NULL)
    )
);


/* =========================================================
 * 7) payment (결제) - 내부/PG 상태 분리
 * ========================================================= */
CREATE TABLE payment (
  payment_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_uid         UUID NOT NULL,

  order_id            BIGINT NOT NULL REFERENCES orders(order_id),

  method              VARCHAR(20) NOT NULL,
  paid_amount         NUMERIC(12,2) NOT NULL DEFAULT 0.00,

  -- 내부(앱) 상태
  app_status          VARCHAR(30) NOT NULL DEFAULT 'REQUESTED',

  -- PG(토스) 원문 status (READY~EXPIRED 등)
  pg_status           VARCHAR(40) NULL,

  -- 토스 paymentKey 전용 컬럼
  pg_payment_key      VARCHAR(100) NULL,

  pg_approval_key     VARCHAR(80) NULL,
  pg_transaction_id   VARCHAR(80) NULL,
  pg_payload          JSONB NULL,

  approved_at         TIMESTAMPTZ(3) NULL,
  canceled_at         TIMESTAMPTZ(3) NULL,

  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_payment_uid UNIQUE (payment_uid),

  CONSTRAINT ck_payment_app_status
    CHECK (app_status IN ('REQUESTED','APPROVED','FAILED','CANCELED','PARTIAL_CANCELED')),

  CONSTRAINT ck_payment_pg_status
    CHECK (
      pg_status IS NULL OR
      pg_status IN (
        'READY','IN_PROGRESS','WAITING_FOR_DEPOSIT','DONE',
        'CANCELED','PARTIAL_CANCELED','ABORTED','EXPIRED'
      )
    )
);

CREATE UNIQUE INDEX uq_payment_pg_payment_key
  ON payment(pg_payment_key)
  WHERE pg_payment_key IS NOT NULL;

CREATE INDEX idx_payment_order_id
  ON payment(order_id);


/* =========================================================
 * 8) pg_webhook_inbox (PG 웹훅 인박스) - event_type 원문 저장
 * ========================================================= */
CREATE TABLE pg_webhook_inbox (
  inbox_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  pg_event_id     VARCHAR(100) NOT NULL,
  event_type      VARCHAR(120) NOT NULL,      -- 원문 그대로 저장(CHK 없음)

  payment_id      BIGINT NULL REFERENCES payment(payment_id),

  payload         JSONB NOT NULL,

  process_status  VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
  retry_count     INT NOT NULL DEFAULT 0,
  last_error      TEXT NULL,

  received_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  processed_at    TIMESTAMPTZ(3) NULL,

  CONSTRAINT uq_pg_event_id UNIQUE (pg_event_id),
  CONSTRAINT ck_pg_webhook_process_status
    CHECK (process_status IN ('RECEIVED','PROCESSED','FAILED')),
  CONSTRAINT ck_pg_webhook_retry_count
    CHECK (retry_count >= 0)
);


/* =========================================================
 * 9) wallet (크레딧 지갑)
 * ========================================================= */
CREATE TABLE wallet (
  wallet_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_type     VARCHAR(20) NOT NULL,
  member_id      BIGINT NULL REFERENCES member(member_id),
  employer_id    BIGINT NULL REFERENCES employer(employer_id),
  balance        INT NOT NULL DEFAULT 0,
  status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_wallet_owner_type CHECK (owner_type IN ('MEMBER','EMPLOYER')),
  CONSTRAINT ck_wallet_owner_fk
    CHECK (
      (owner_type='MEMBER'   AND member_id IS NOT NULL AND employer_id IS NULL) OR
      (owner_type='EMPLOYER' AND employer_id IS NOT NULL AND member_id IS NULL)
    )
);

CREATE UNIQUE INDEX uq_wallet_member_one
  ON wallet(member_id) WHERE member_id IS NOT NULL;

CREATE UNIQUE INDEX uq_wallet_employer_one
  ON wallet(employer_id) WHERE employer_id IS NOT NULL;


/* =========================================================
 * 10) wallet_ledger (크레딧 원장)
 * ========================================================= */
CREATE TABLE wallet_ledger (
  ledger_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id        BIGINT NOT NULL REFERENCES wallet(wallet_id),
  tx_type          VARCHAR(10) NOT NULL,
  source_type      VARCHAR(30) NOT NULL,
  source_ref_id    BIGINT NULL,
  amount           INT NOT NULL,
  balance_before   INT NOT NULL,
  balance_after    INT NOT NULL,
  idempotency_key  VARCHAR(100) NOT NULL,
  memo             VARCHAR(200) NULL,
  occurred_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_wallet_ledger_idem UNIQUE (idempotency_key),
  CONSTRAINT ck_wallet_ledger_tx_type CHECK (tx_type IN ('CREDIT','DEBIT')),
  CONSTRAINT ck_wallet_ledger_source_type
    CHECK (source_type IN ('PAYMENT','SUBSCRIPTION','AI','AD_CLICK','MANUAL'))
);

CREATE INDEX idx_wallet_ledger_wallet_occurred
  ON wallet_ledger(wallet_id, occurred_at DESC);


/* =========================================================
 * 11) subscription (구독) ✅ customer_key / billing_key
 * ========================================================= */
CREATE TABLE subscription (
  subscription_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id      BIGINT NOT NULL REFERENCES employer(employer_id),
  product_id       BIGINT NOT NULL REFERENCES product(product_id),
  status           VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  started_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  next_billing_at  TIMESTAMPTZ(3) NULL,
  ended_at         TIMESTAMPTZ(3) NULL,

  customer_key     VARCHAR(80) NULL,
  billing_key      VARCHAR(200) NULL,

  created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_subscription_status CHECK (status IN ('ACTIVE','CANCELED','PAYMENT_FAILED'))
);


/* =========================================================
 * 12) subscription_billing_cycle (구독 청구 사이클)
 * ========================================================= */
CREATE TABLE subscription_billing_cycle (
  cycle_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  subscription_id  BIGINT NOT NULL REFERENCES subscription(subscription_id),
  billing_month    DATE NOT NULL, -- YYYY-MM-01

  payment_id       BIGINT NULL REFERENCES payment(payment_id),

  credit_grant     INT NOT NULL,
  ledger_id        BIGINT NULL REFERENCES wallet_ledger(ledger_id),

  payment_status   VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED', -- SCHEDULED/PAID/FAILED
  credit_status    VARCHAR(20) NOT NULL DEFAULT 'PENDING',   -- PENDING/GRANTED/FAILED/REVOKED

  created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_subscription_billing UNIQUE (subscription_id, billing_month),

  CONSTRAINT ck_cycle_payment_status
    CHECK (payment_status IN ('SCHEDULED','PAID','FAILED')),
  CONSTRAINT ck_cycle_credit_status
    CHECK (credit_status IN ('PENDING','GRANTED','FAILED','REVOKED'))
);


-- =========================================================
-- 13) job_posting (채용공고) ✅ 원본 유지 + 스택 배열화/경력 필드 추가
-- =========================================================
CREATE TABLE job_posting (
  job_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id         BIGINT NOT NULL REFERENCES employer(employer_id),
  title               VARCHAR(200) NOT NULL,
  description         TEXT NOT NULL,
  status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  location            VARCHAR(120) NULL,
  salary_text         BIGINT NULL,
  required_questions  JSONB NULL,
  view_count          INT NOT NULL DEFAULT 0,
  apply_count         INT NOT NULL DEFAULT 0,

  -- ✅ 변경: VARCHAR(80) -> TEXT[] (기술 스택 배열)
  stack              TEXT[] NULL,           
  
  -- ✅ 신규 추가: 최소 요구 경력 연수 (0: 신입/무관)
  required_experience INT NOT NULL DEFAULT 0,

  summary             TEXT NULL,             -- 파이썬 요약본
  embedding           vector(1536) NULL,     -- pgvector

  -- ✅ 광고 입찰가(credit): "광고 아님=0" 정규화
  ad_bid_credit       INT NOT NULL DEFAULT 0,

  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at          TIMESTAMPTZ(3) NULL,

  CONSTRAINT ck_job_posting_status CHECK (status IN ('DRAFT','OPEN','CLOSED')),
  CONSTRAINT ck_job_posting_counts CHECK (view_count >= 0 AND apply_count >= 0),
  CONSTRAINT ck_job_posting_ad_bid_credit_nonneg CHECK (ad_bid_credit >= 0)
);

CREATE INDEX idx_job_posting_employer_status
  ON job_posting(employer_id, status);

-- ✅ 변경: stack -> stack (배열 타입 반영) 및 GIN 인덱스 추가
CREATE INDEX idx_job_posting_stack_gin ON job_posting USING GIN (stack);

-- ✅ 0.1초 이내 프리필터링: OPEN + 광고(credit>0)만 먼저 추출 (stack 필드 반영)
CREATE INDEX idx_job_posting_ads_prefilter
  ON job_posting (stack, ad_bid_credit DESC, job_id)
  WHERE deleted_at IS NULL
    AND status = 'OPEN'
    AND ad_bid_credit > 0;

COMMENT ON COLUMN job_posting.ad_bid_credit IS
'광고 입찰가(credit). RTB 우선순위/AI유사도+비즈가치 하이브리드 스코어/광고만 프리필터링 용도.';
COMMENT ON COLUMN job_posting.required_experience IS '채용을 위해 요구되는 최소 경력 연수 (0: 신입)';


-- =========================================================
-- 14) resume (이력서/포트폴리오/자기소개서) ✅ 원본 유지 + 스택 배열화/경력 필드 추가
-- =========================================================
CREATE TABLE resume (
  resume_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id            BIGINT NOT NULL REFERENCES member(member_id),
  title                VARCHAR(120) NOT NULL,
  tagline              VARCHAR(200) NULL,

  is_primary           BOOLEAN NOT NULL DEFAULT FALSE,
  is_public            BOOLEAN NOT NULL DEFAULT FALSE,
  status               VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  last_modified_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  created_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at           TIMESTAMPTZ(3) NULL,

  target_job_id        BIGINT NULL REFERENCES job_posting(job_id),
  content              TEXT NULL,
  field                VARCHAR(20) NOT NULL,       -- RESUME/PORTFOLIO/INTRO

  summary              TEXT NULL,                  -- AI 요약
  embedding            vector(1536) NULL,          -- AI 임베딩

  -- ✅ AI 요약 상태(비동기 무결성/추적/중복방지)
  summary_status       VARCHAR(20) NOT NULL DEFAULT 'NONE',

  preference_location  VARCHAR(80) NULL,
  preference_salary    VARCHAR(80) NULL,
  employment_type      VARCHAR(80) NULL,           -- ✅ 오탈자 수정 완료
  
  -- ✅ 변경: TEXT -> TEXT[] (보유 기술 스택 배열)
  re_stack            TEXT[] NULL,                

  -- ✅ 신규 추가: 직무 관련 총 경력 연수 (사용자 확정값)
  career_years         INT NOT NULL DEFAULT 0,

  school               TEXT NULL,
  school_state         TEXT NULL,                  -- ADM/RET/GRD
  school_class         TEXT NULL,

  CONSTRAINT ck_resume_status CHECK (status IN ('DRAFT','ACTIVE','DELETED')),
  CONSTRAINT ck_resume_field  CHECK (field IN ('RESUME','PORTFOLIO','INTRO')),

  -- ✅ DEFAULT/CHK 불일치 해결: NONE 포함
  CONSTRAINT ck_resume_summary_status
    CHECK (summary_status IN ('NONE','PENDING','PROCESSING','COMPLETED','FAILED')),

  -- ✅ COMPLETED 데이터만 사용자 노출 정책과 정합성
  CONSTRAINT ck_resume_summary_completed_has_summary
    CHECK (summary_status <> 'COMPLETED' OR summary IS NOT NULL)
);

-- 인덱스 설정
CREATE INDEX idx_resume_member_status
  ON resume(member_id, status);

-- ✅ 신규 추가: 이력서 스택 검색용 GIN 인덱스
CREATE INDEX idx_resume_re_stack_gin ON resume USING GIN (re_stack);

-- ✅ 워커 todo(대기/실패) 픽업 인덱스
CREATE INDEX idx_resume_summary_todo
  ON resume (summary_status, updated_at DESC, resume_id)
  WHERE summary_status IN ('PENDING','FAILED');

-- 코멘트 추가
COMMENT ON COLUMN resume.summary_status IS 'AI 요약 비동기 상태: NONE(미요청)/PENDING/PROCESSING/COMPLETED/FAILED';
COMMENT ON COLUMN resume.re_stack IS '사용자가 보유한 기술 스택 목록 (배열)';
COMMENT ON COLUMN resume.career_years IS '사용자가 직접 입력/확정한 직무 관련 총 경력 연수';

-- =========================================================
-- 15) job_application (지원)
-- =========================================================
CREATE TABLE job_application (
  application_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id                BIGINT NOT NULL REFERENCES job_posting(job_id),
  member_id             BIGINT NOT NULL REFERENCES member(member_id),
  resume_id             BIGINT NOT NULL REFERENCES resume(resume_id),
  status                VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
  answers               JSONB NULL,
  applied_at            TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  canceled_at           TIMESTAMPTZ(3) NULL,
  viewed_at             TIMESTAMPTZ(3) NULL,
  contact_disclosed_at  TIMESTAMPTZ(3) NULL,
  created_at            TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_job_application UNIQUE (job_id, member_id),
  CONSTRAINT ck_job_application_status
    CHECK (status IN ('SUBMITTED','VIEWED','INTERVIEW','HIRED','REJECTED','CANCELED'))
);


-- =========================================================
-- 16) interview_schedule (면접 일정)
-- =========================================================
CREATE TABLE interview_schedule (
  interview_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id       BIGINT NOT NULL REFERENCES job_application(application_id),
  stage                VARCHAR(20) NOT NULL,
  method               VARCHAR(20) NOT NULL,
  location             VARCHAR(200) NULL,
  meeting_url          TEXT NULL,
  start_at             TIMESTAMPTZ(3) NOT NULL,
  end_at               TIMESTAMPTZ(3) NOT NULL,
  status               VARCHAR(20) NOT NULL DEFAULT 'PROPOSED',
  created_by_member_id BIGINT NULL REFERENCES member(member_id),
  created_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_interview_stage CHECK (stage IN ('1ST','2ND','FINAL')),
  CONSTRAINT ck_interview_method CHECK (method IN ('ONSITE','VIDEO','PHONE')),
  CONSTRAINT ck_interview_status CHECK (status IN ('PROPOSED','CONFIRMED','CANCELED','DONE')),
  CONSTRAINT ck_interview_time CHECK (end_at > start_at)
);


-- =========================================================
-- 17) interview_response (면접 제안 응답)
-- =========================================================
CREATE TABLE interview_response (
  response_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interview_id    BIGINT NOT NULL REFERENCES interview_schedule(interview_id),
  response        VARCHAR(20) NOT NULL,
  message         TEXT NULL,
  responded_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_interview_response CHECK (response IN ('ACCEPT','DECLINE','REQUEST_CHANGE'))
);


-- =========================================================
-- 18) resume_profile (이력서 기본정보 1:1)
-- =========================================================
CREATE TABLE resume_profile (
  profile_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id    BIGINT NOT NULL REFERENCES resume(resume_id),
  address      VARCHAR(200) NULL,
  photo_url    TEXT NULL,

  CONSTRAINT uq_resume_profile UNIQUE (resume_id)
);


-- =========================================================
-- 19) resume_project (프로젝트)
-- =========================================================
CREATE TABLE resume_project (
  project_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id           BIGINT NOT NULL REFERENCES resume(resume_id),
  title               VARCHAR(120) NOT NULL,
  start_date          DATE NULL,
  end_date            DATE NULL,
  contribution_pct    NUMERIC(5,2) NULL,
  tech_stack          TEXT[] NULL,
  description         TEXT NULL,
  sort_order          INT NOT NULL DEFAULT 0,
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);


-- =========================================================
-- 20) resume_attachment (이력서 첨부파일) ✅ ai_description
-- =========================================================
CREATE TABLE resume_attachment (
  attachment_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id       BIGINT NOT NULL REFERENCES resume(resume_id),
  file_url        TEXT NOT NULL,
  file_name       VARCHAR(200) NOT NULL,
  mime_type       VARCHAR(80) NULL,
  file_size       BIGINT NULL,
  scan_status     VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  copyright_ok    BOOLEAN NOT NULL DEFAULT FALSE,

  ai_description  TEXT NULL,

  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_resume_attachment_scan_status CHECK (scan_status IN ('PENDING','PASSED','FAILED'))
);


-- =========================================================
-- 21) resume_link (이력서 링크)
-- =========================================================
CREATE TABLE resume_link (
  link_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id    BIGINT NOT NULL REFERENCES resume(resume_id),
  link_type    VARCHAR(20) NOT NULL,
  url          TEXT NOT NULL,
  created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_resume_link_type CHECK (link_type IN ('GITHUB','BLOG','ETC'))
);


-- =========================================================
-- 22) resume_career (경력 상세)
-- =========================================================
CREATE TABLE resume_career (
  career_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id       BIGINT NOT NULL REFERENCES resume(resume_id),
  company_name    VARCHAR(100) NOT NULL,
  department      VARCHAR(100) NOT NULL,
  role            VARCHAR(100) NOT NULL,
  start_date      DATE NOT NULL,
  end_date        DATE NULL,
  is_current      BOOLEAN NULL,
  is_verified     BOOLEAN NULL,
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_resume_career_dates
    CHECK (
      (is_current IS TRUE AND end_date IS NULL)
      OR (is_current IS DISTINCT FROM TRUE AND (end_date IS NULL OR end_date >= start_date))
    )
);

CREATE INDEX idx_resume_career_resume_id ON resume_career(resume_id);


-- =========================================================
-- 23) resume_certificate (자격증 상세)
-- =========================================================
CREATE TABLE resume_certificate (
  resume_certificate_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id              BIGINT NOT NULL REFERENCES resume(resume_id),
  name                   VARCHAR(100) NOT NULL,
  issuer                 VARCHAR(100) NOT NULL,
  acquisition_date       DATE NOT NULL,
  is_verified            BOOLEAN NULL,
  created_at             TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);

CREATE INDEX idx_resume_certificate_resume_id ON resume_certificate(resume_id);


-- =========================================================
-- 24) job_scrap (공고 스크랩)
-- =========================================================
CREATE TABLE job_scrap (
  scrap_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id    BIGINT NOT NULL REFERENCES member(member_id),
  job_id       BIGINT NOT NULL REFERENCES job_posting(job_id),
  created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_job_scrap UNIQUE (member_id, job_id)
);


-- =========================================================
-- 25) job_view_log (공고 열람 로그)
-- =========================================================
CREATE TABLE job_view_log (
  view_log_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id    BIGINT NULL REFERENCES member(member_id),
  job_id       BIGINT NOT NULL REFERENCES job_posting(job_id),
  viewed_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);


-- =========================================================
-- 26) ad_campaign (광고 캠페인)
-- =========================================================
CREATE TABLE ad_campaign (
  campaign_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id    BIGINT NOT NULL REFERENCES employer(employer_id),
  job_id         BIGINT NOT NULL REFERENCES job_posting(job_id),
  cpc_bid        INT NOT NULL,
  daily_budget   INT NOT NULL,
  status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  start_at       TIMESTAMPTZ(3) NULL,
  end_at         TIMESTAMPTZ(3) NULL,
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_ad_campaign_status CHECK (status IN ('ACTIVE','PAUSED','ENDED'))
);


-- =========================================================
-- 27) ad_click_event (광고 클릭 이벤트)
-- =========================================================
CREATE TABLE ad_click_event (
  click_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id   BIGINT NOT NULL REFERENCES ad_campaign(campaign_id),
  member_id     BIGINT NULL REFERENCES member(member_id),
  click_key     VARCHAR(120) NOT NULL,
  ledger_id     BIGINT NULL REFERENCES wallet_ledger(ledger_id),
  occurred_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_ad_click_key UNIQUE (click_key)
);


-- =========================================================
-- 28) inquiry (고객문의)
-- =========================================================
CREATE TABLE inquiry (
  inquiry_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id        BIGINT NOT NULL REFERENCES member(member_id),
  title            VARCHAR(200) NOT NULL,
  status           VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  answered_at      TIMESTAMPTZ(3) NULL,
  retention_until  TIMESTAMPTZ(3) NULL,
  created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_inquiry_status CHECK (status IN ('OPEN','ANSWERED','CLOSED'))
);


-- =========================================================
-- 29) inquiry_message (문의 메시지)
-- =========================================================
CREATE TABLE inquiry_message (
  message_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inquiry_id           BIGINT NOT NULL REFERENCES inquiry(inquiry_id),
  author_type          VARCHAR(20) NOT NULL,
  admin_member_id      BIGINT NULL REFERENCES member(member_id),
  body                 TEXT NOT NULL,
  created_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_inquiry_author_type CHECK (author_type IN ('CUSTOMER','ADMIN'))
);


-- =========================================================
-- 30) notice (공지 + 정책문서 저장소로 재사용)
-- =========================================================
CREATE TABLE notice (
  notice_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title          VARCHAR(200) NOT NULL,
  body           TEXT NOT NULL,
  is_public      BOOLEAN NOT NULL DEFAULT TRUE,
  notice_type    VARCHAR(30) NOT NULL DEFAULT 'OPS',
  status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  purge_after    TIMESTAMPTZ(3) NULL,
  created_by     BIGINT NULL REFERENCES member(member_id),
  updated_by     BIGINT NULL REFERENCES member(member_id),
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at     TIMESTAMPTZ(3) NULL,

  CONSTRAINT ck_notice_type CHECK (notice_type IN ('OPS','POLICY','PRIVACY','TERMS')),
  CONSTRAINT ck_notice_status CHECK (status IN ('ACTIVE','PENDING_DELETE','DELETED'))
);

CREATE UNIQUE INDEX uq_notice_active_policy_per_type
  ON notice(notice_type)
  WHERE deleted_at IS NULL
    AND status = 'ACTIVE'
    AND notice_type IN ('TERMS','PRIVACY','POLICY');

CREATE INDEX idx_notice_type_status_created
  ON notice(notice_type, status, created_at DESC);


-- =========================================================
-- 31) notice_attachment (공지/정책 첨부)
-- =========================================================
CREATE TABLE notice_attachment (
  attachment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id      BIGINT NOT NULL REFERENCES notice(notice_id),
  file_url       TEXT NOT NULL,
  file_name      VARCHAR(200) NOT NULL,
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);


-- =========================================================
-- 32) notice_delivery (공지 개별 발송)
-- =========================================================
CREATE TABLE notice_delivery (
  delivery_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id     BIGINT NOT NULL REFERENCES notice(notice_id),
  member_id     BIGINT NOT NULL REFERENCES member(member_id),
  channel       VARCHAR(20) NOT NULL,
  status        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  sent_at       TIMESTAMPTZ(3) NULL,
  fail_reason   VARCHAR(200) NULL,
  created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_notice_delivery_channel CHECK (channel IN ('EMAIL','SMS','LMS','PUSH')),
  CONSTRAINT ck_notice_delivery_status CHECK (status IN ('PENDING','SENT','FAILED'))
);


-- =========================================================
-- ✅ member -> notice FK (순환 참조 방지 위해 notice 생성 이후 추가)
-- =========================================================
ALTER TABLE member
  ADD CONSTRAINT fk_member_terms_notice
    FOREIGN KEY (terms_notice_id) REFERENCES notice(notice_id);

ALTER TABLE member
  ADD CONSTRAINT fk_member_privacy_notice
    FOREIGN KEY (privacy_notice_id) REFERENCES notice(notice_id);

ALTER TABLE member
  ADD CONSTRAINT fk_member_policy_notice
    FOREIGN KEY (policy_notice_id) REFERENCES notice(notice_id);


-- =========================================================
-- 33) faq (FAQ)
-- =========================================================
CREATE TABLE faq (
  faq_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question    TEXT NOT NULL,
  answer      TEXT NOT NULL,
  locked      BOOLEAN NOT NULL DEFAULT TRUE,
  is_public   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ(3) NULL
);


-- =========================================================
-- 34) report (신고)
-- =========================================================
CREATE TABLE report (
  report_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_member_id  BIGINT NOT NULL REFERENCES member(member_id),
  target_type         VARCHAR(20) NOT NULL,
  target_job_id       BIGINT NULL REFERENCES job_posting(job_id),
  reason_code         VARCHAR(30) NOT NULL,
  reason_detail       TEXT NULL,
  status              VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_report_target_type CHECK (target_type IN ('JOB_POSTING','MEMBER','ETC')),
  CONSTRAINT ck_report_status CHECK (status IN ('OPEN','ACCEPTED','REJECTED'))
);


-- =========================================================
-- 35) moderation_action (신고 처리)
-- =========================================================
CREATE TABLE moderation_action (
  action_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id        BIGINT NOT NULL REFERENCES report(report_id),
  admin_member_id  BIGINT NULL REFERENCES member(member_id),
  decision         VARCHAR(20) NOT NULL,
  sanction_level   INT NULL,
  restrict_days    INT NULL,
  reason           TEXT NOT NULL,
  decided_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_moderation_action_report UNIQUE (report_id),
  CONSTRAINT ck_moderation_decision CHECK (decision IN ('ACCEPT','REJECT'))
);


-- =========================================================
-- 36) member_penalty_point (경고 점수)
-- =========================================================
CREATE TABLE member_penalty_point (
  penalty_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id    BIGINT NOT NULL REFERENCES member(member_id),
  report_id    BIGINT NULL REFERENCES report(report_id),
  points       INT NOT NULL,
  reason       VARCHAR(200) NOT NULL,
  created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);


-- =========================================================
-- 37) notification_template (알림 템플릿)
-- =========================================================
CREATE TABLE notification_template (
  template_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_code  VARCHAR(50) NOT NULL,
  channel        VARCHAR(20) NOT NULL,
  subject        VARCHAR(200) NULL,
  body           TEXT NOT NULL,
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_notification_template_code UNIQUE (template_code),
  CONSTRAINT ck_notification_channel CHECK (channel IN ('EMAIL','SMS','PUSH'))
);


-- =========================================================
-- 38) notification_delivery (알림 발송 이력)
-- =========================================================
CREATE TABLE notification_delivery (
  delivery_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id   BIGINT NULL REFERENCES notification_template(template_id),
  member_id     BIGINT NOT NULL REFERENCES member(member_id),
  event_type    VARCHAR(40) NOT NULL,
  channel       VARCHAR(20) NOT NULL,
  status        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  sent_at       TIMESTAMPTZ(3) NULL,
  payload       JSONB NULL,
  created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_notification_delivery_status CHECK (status IN ('PENDING','SENT','FAILED')),
  CONSTRAINT ck_notification_delivery_channel CHECK (channel IN ('EMAIL','SMS','PUSH'))
);


-- =========================================================
-- 39) outbox_event (아웃박스 이벤트)
-- =========================================================
CREATE TABLE outbox_event (
  outbox_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type      VARCHAR(50) NOT NULL,
  aggregate_type  VARCHAR(30) NOT NULL,
  aggregate_id    BIGINT NOT NULL,
  payload         JSONB NOT NULL,
  status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  retry_count     INT NOT NULL DEFAULT 0,
  next_run_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  locked_at       TIMESTAMPTZ(3) NULL,
  locked_by       VARCHAR(80) NULL,
  last_error      TEXT NULL,
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  processed_at    TIMESTAMPTZ(3) NULL,

  CONSTRAINT ck_outbox_status CHECK (status IN ('PENDING','PROCESSING','SUCCEEDED','FAILED'))
);

CREATE INDEX idx_outbox_pick
  ON outbox_event(status, next_run_at, outbox_id);

CREATE INDEX idx_outbox_agg
  ON outbox_event(aggregate_type, aggregate_id);


-- =========================================================
-- A) wallet_credit_lot (결제별 크레딧 LOT)
-- =========================================================
CREATE TABLE wallet_credit_lot (
  lot_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id           BIGINT NOT NULL REFERENCES wallet(wallet_id),
  payment_id          BIGINT NOT NULL REFERENCES payment(payment_id),

  granted_credit      INT NOT NULL,
  remaining_credit    INT NOT NULL,

  unit_price_amount   NUMERIC(12,2) NOT NULL,
  currency            CHAR(3) NOT NULL DEFAULT 'KRW',
  pricing_meta        JSONB NULL,

  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT ck_wallet_credit_lot_credit
    CHECK (
      granted_credit >= 0
      AND remaining_credit >= 0
      AND remaining_credit <= granted_credit
    )
);

CREATE UNIQUE INDEX uq_wallet_credit_lot_wallet_payment
  ON wallet_credit_lot(wallet_id, payment_id);

CREATE INDEX idx_wallet_credit_lot_wallet_created
  ON wallet_credit_lot(wallet_id, created_at ASC);


-- =========================================================
-- B) payment_cancel (토스 취소/환불 이력) - cancel_status(원문)
-- =========================================================
CREATE TABLE payment_cancel (
  cancel_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id             BIGINT NOT NULL REFERENCES payment(payment_id),

  toss_transaction_key   VARCHAR(80) NOT NULL,

  cancel_status          VARCHAR(40) NULL,  -- 원문 예: DONE 등

  cancel_amount          NUMERIC(12,2) NOT NULL,
  cancel_reason          VARCHAR(200) NOT NULL,
  canceled_at            TIMESTAMPTZ(3) NULL,

  idempotency_key        VARCHAR(100) NOT NULL,
  raw_cancel             JSONB NULL,

  created_at             TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  CONSTRAINT uq_payment_cancel_tx UNIQUE (payment_id, toss_transaction_key),
  CONSTRAINT uq_payment_cancel_idem UNIQUE (idempotency_key),
  CONSTRAINT ck_payment_cancel_amount CHECK (cancel_amount > 0)
);

CREATE INDEX idx_payment_cancel_payment_created
  ON payment_cancel(payment_id, created_at DESC);


-- =========================================================
-- updated_at 자동 갱신 트리거 적용 (updated_at 컬럼 있는 테이블만)
-- =========================================================
CREATE TRIGGER trg_set_updated_at_member
BEFORE UPDATE ON member
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_employer
BEFORE UPDATE ON employer
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_product
BEFORE UPDATE ON product
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_orders
BEFORE UPDATE ON orders
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_payment
BEFORE UPDATE ON payment
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_wallet
BEFORE UPDATE ON wallet
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_subscription
BEFORE UPDATE ON subscription
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_job_posting
BEFORE UPDATE ON job_posting
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_resume
BEFORE UPDATE ON resume
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_job_application
BEFORE UPDATE ON job_application
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_interview_schedule
BEFORE UPDATE ON interview_schedule
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_resume_project
BEFORE UPDATE ON resume_project
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_resume_career
BEFORE UPDATE ON resume_career
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_resume_certificate
BEFORE UPDATE ON resume_certificate
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_inquiry
BEFORE UPDATE ON inquiry
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_notice
BEFORE UPDATE ON notice
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_faq
BEFORE UPDATE ON faq
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_ad_campaign
BEFORE UPDATE ON ad_campaign
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_outbox_event
BEFORE UPDATE ON outbox_event
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at_wallet_credit_lot
BEFORE UPDATE ON wallet_credit_lot
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
