-- ================================================================
-- FitMe PostgreSQL 전체 스키마
-- 다른 PC에서 바로 실행 가능 (IF NOT EXISTS 적용)
-- DB: fitme_project / User: postgres
-- 최종 수정: 2026-02-03
-- ================================================================
-- 실행 방법:
-- psql -U postgres -d fitme_project -f ERD_Table_0202.txt
-- ================================================================

-- ================================================================
-- PART 1: 확장 및 함수
-- ================================================================
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


-- ================================================================
-- PART 2: 테이블 생성 (의존성 순서)
-- ================================================================

-- 1) notice (member FK 참조용으로 먼저 생성)
CREATE TABLE IF NOT EXISTS notice (
  notice_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title          VARCHAR(200) NOT NULL,
  body           TEXT NOT NULL,
  is_public      BOOLEAN NOT NULL DEFAULT TRUE,
  notice_type    VARCHAR(30) NOT NULL DEFAULT 'OPS',
  status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  purge_after    TIMESTAMPTZ(3) NULL,
  created_by     BIGINT NULL,
  updated_by     BIGINT NULL,
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at     TIMESTAMPTZ(3) NULL,
  CONSTRAINT ck_notice_type CHECK (notice_type IN ('OPS','POLICY','PRIVACY','TERMS')),
  CONSTRAINT ck_notice_status CHECK (status IN ('ACTIVE','PENDING_DELETE','DELETED'))
);

CREATE INDEX IF NOT EXISTS idx_notice_type_status_created ON notice(notice_type, status, created_at DESC);


-- 2) member
CREATE TABLE IF NOT EXISTS member (
  member_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_uid              UUID NOT NULL,
  email                   VARCHAR(320) NOT NULL,
  login_id                VARCHAR(50) NULL,
  auth_provider           VARCHAR(20) NOT NULL DEFAULT 'OTHER',
  password_hash           VARCHAR(255) NULL,
  name                    VARCHAR(80) NOT NULL,
  gender                  VARCHAR(20) NULL,
  birth_date              DATE NULL,
  phone                   VARCHAR(20) NULL,
  role                    VARCHAR(20) NOT NULL,
  status                  VARCHAR(20) NOT NULL,
  last_login_at           TIMESTAMPTZ(3) NULL,
  password_changed_at     TIMESTAMPTZ(3) NULL,
  failed_login_count      INT NOT NULL DEFAULT 0,
  locked_until            TIMESTAMPTZ(3) NULL,
  phone_verified_at       TIMESTAMPTZ(3) NULL,
  created_at              TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at              TIMESTAMPTZ(3) NULL,
  terms_notice_id         BIGINT NULL REFERENCES notice(notice_id),
  terms_agreed_at         TIMESTAMPTZ(3) NULL,
  privacy_notice_id       BIGINT NULL REFERENCES notice(notice_id),
  privacy_agreed_at       TIMESTAMPTZ(3) NULL,
  policy_notice_id        BIGINT NULL REFERENCES notice(notice_id),
  policy_agreed_at        TIMESTAMPTZ(3) NULL,
  marketing_opt_in        BOOLEAN NOT NULL DEFAULT FALSE,
  marketing_agreed_at     TIMESTAMPTZ(3) NULL,
  consent_ip              VARCHAR(45) NULL,
  consent_user_agent      TEXT NULL,
  CONSTRAINT uq_member_uid UNIQUE (member_uid),
  CONSTRAINT uq_member_email UNIQUE (email),
  CONSTRAINT ck_member_role CHECK (role IN ('CANDIDATE','EMPLOYER','SERVICEADMIN','APPROVEADMIN','MASTER')),
  CONSTRAINT ck_member_status CHECK (status IN ('ACTIVE','SUSPENDED','WITHDRAWN')),
  CONSTRAINT ck_member_failed_login_count CHECK (failed_login_count >= 0),
  CONSTRAINT ck_member_auth_provider CHECK (auth_provider IN ('NAVER','GOOGLE','KAKAO','OTHER')),
  CONSTRAINT ck_member_gender CHECK (gender IS NULL OR gender IN ('MALE','FEMALE'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_member_login_id_active ON member(login_id) WHERE deleted_at IS NULL AND login_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_member_phone_verified_active ON member(phone) WHERE deleted_at IS NULL AND phone IS NOT NULL AND phone_verified_at IS NOT NULL;


-- 3) phone_verification
CREATE TABLE IF NOT EXISTS phone_verification (
  verification_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phone               VARCHAR(20) NOT NULL,
  purpose             VARCHAR(20) NOT NULL,
  code_hash           CHAR(64) NOT NULL,
  expires_at          TIMESTAMPTZ(3) NOT NULL,
  verified_at         TIMESTAMPTZ(3) NULL,
  consumed_at         TIMESTAMPTZ(3) NULL,
  attempt_count       INT NOT NULL DEFAULT 0,
  resend_count        INT NOT NULL DEFAULT 0,
  last_sent_at        TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  request_ip          VARCHAR(45) NULL,
  request_user_agent  TEXT NULL,
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT ck_phone_verification_purpose CHECK (purpose IN ('SIGNUP','PASSWORD_RESET','PHONE_LINK')),
  CONSTRAINT ck_phone_verification_attempt CHECK (attempt_count >= 0),
  CONSTRAINT ck_phone_verification_resend CHECK (resend_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_phone_verification_phone_purpose_created ON phone_verification(phone, purpose, created_at DESC);


-- 4) member_login_log
CREATE TABLE IF NOT EXISTS member_login_log (
  login_log_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id       BIGINT NOT NULL REFERENCES member(member_id),
  success         BOOLEAN NOT NULL DEFAULT FALSE,
  ip_address      VARCHAR(45) NULL,
  user_agent      TEXT NULL,
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_member_login_log_member_created ON member_login_log(member_id, created_at DESC);


-- 5) employer
CREATE TABLE IF NOT EXISTS employer (
  employer_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_uid    UUID NOT NULL,
  name            VARCHAR(120) NOT NULL,
  logo_url        TEXT NULL,
  industry        VARCHAR(80) NULL,
  founded_year    INT NULL,
  employee_count  INT NULL,
  location        VARCHAR(120) NULL,
  description     TEXT NULL,
  culture         TEXT NULL,
  benefits        TEXT NULL,
  tech_stack      TEXT NULL,
  contact_email   VARCHAR(320) NULL,
  contact_phone   VARCHAR(20) NULL,
  website_url     TEXT NULL,
  status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at      TIMESTAMPTZ(3) NULL,
  CONSTRAINT uq_employer_uid UNIQUE (employer_uid),
  CONSTRAINT ck_employer_status CHECK (status IN ('ACTIVE','SUSPENDED','CLOSED'))
);

CREATE INDEX IF NOT EXISTS idx_employer_name ON employer(name);


-- 6) employer_member
CREATE TABLE IF NOT EXISTS employer_member (
  employer_member_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id          BIGINT NOT NULL REFERENCES employer(employer_id),
  member_id            BIGINT NOT NULL REFERENCES member(member_id),
  role_in_company      VARCHAR(20) NOT NULL,
  active               BOOLEAN NOT NULL DEFAULT TRUE,
  created_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_employer_member UNIQUE (employer_id, member_id),
  CONSTRAINT ck_role_in_company CHECK (role_in_company IN ('OWNER','HR','STAFF'))
);


-- 7) product
CREATE TABLE IF NOT EXISTS product (
  product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_code    VARCHAR(40) NOT NULL,
  product_type    VARCHAR(20) NOT NULL,
  name            VARCHAR(120) NOT NULL,
  sale_status     VARCHAR(20) NOT NULL,
  price_amount    NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  currency        CHAR(3) NOT NULL DEFAULT 'KRW',
  credit_amount   INT NULL,
  plan_tier       VARCHAR(20) NULL,
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at      TIMESTAMPTZ(3) NULL,
  CONSTRAINT uq_product_code UNIQUE (product_code),
  CONSTRAINT ck_product_type CHECK (product_type IN ('ONE_TIME','SUBSCRIPTION')),
  CONSTRAINT ck_sale_status CHECK (sale_status IN ('ON_SALE','PAUSED','STOPPED'))
);


-- 8) orders
CREATE TABLE IF NOT EXISTS orders (
  order_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_uid           UUID NOT NULL,
  buyer_type          VARCHAR(20) NOT NULL,
  buyer_member_id     BIGINT NULL REFERENCES member(member_id),
  buyer_employer_id   BIGINT NULL REFERENCES employer(employer_id),
  product_id          BIGINT NOT NULL REFERENCES product(product_id),
  order_amount        NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  status              VARCHAR(20) NOT NULL DEFAULT 'CREATED',
  idempotency_key     VARCHAR(64) NOT NULL,
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_order_uid UNIQUE (order_uid),
  CONSTRAINT uq_orders_idempotency UNIQUE (idempotency_key),
  CONSTRAINT ck_orders_buyer_type CHECK (buyer_type IN ('MEMBER','EMPLOYER')),
  CONSTRAINT ck_orders_status CHECK (status IN ('CREATED','PAID','CANCELED','FAILED'))
);


-- 9) payment
CREATE TABLE IF NOT EXISTS payment (
  payment_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_uid         UUID NOT NULL,
  order_id            BIGINT NOT NULL REFERENCES orders(order_id),
  method              VARCHAR(20) NOT NULL,
  paid_amount         NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  app_status          VARCHAR(30) NOT NULL DEFAULT 'REQUESTED',
  pg_status           VARCHAR(40) NULL,
  pg_payment_key      VARCHAR(100) NULL,
  pg_approval_key     VARCHAR(80) NULL,
  pg_transaction_id   VARCHAR(80) NULL,
  pg_payload          JSONB NULL,
  approved_at         TIMESTAMPTZ(3) NULL,
  canceled_at         TIMESTAMPTZ(3) NULL,
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_payment_uid UNIQUE (payment_uid),
  CONSTRAINT ck_payment_app_status CHECK (app_status IN ('REQUESTED','APPROVED','FAILED','CANCELED','PARTIAL_CANCELED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_pg_payment_key ON payment(pg_payment_key) WHERE pg_payment_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payment_order_id ON payment(order_id);


-- 10) pg_webhook_inbox
CREATE TABLE IF NOT EXISTS pg_webhook_inbox (
  inbox_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pg_event_id     VARCHAR(100) NOT NULL,
  event_type      VARCHAR(120) NOT NULL,
  payment_id      BIGINT NULL REFERENCES payment(payment_id),
  payload         JSONB NOT NULL,
  process_status  VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
  retry_count     INT NOT NULL DEFAULT 0,
  last_error      TEXT NULL,
  received_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  processed_at    TIMESTAMPTZ(3) NULL,
  CONSTRAINT uq_pg_event_id UNIQUE (pg_event_id),
  CONSTRAINT ck_pg_webhook_process_status CHECK (process_status IN ('RECEIVED','PROCESSED','FAILED'))
);


-- 11) wallet
CREATE TABLE IF NOT EXISTS wallet (
  wallet_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_type     VARCHAR(20) NOT NULL,
  member_id      BIGINT NULL REFERENCES member(member_id),
  employer_id    BIGINT NULL REFERENCES employer(employer_id),
  balance        INT NOT NULL DEFAULT 0,
  status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT ck_wallet_owner_type CHECK (owner_type IN ('MEMBER','EMPLOYER'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_wallet_member_one ON wallet(member_id) WHERE member_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_wallet_employer_one ON wallet(employer_id) WHERE employer_id IS NOT NULL;


-- 12) wallet_ledger
CREATE TABLE IF NOT EXISTS wallet_ledger (
  ledger_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id        BIGINT NOT NULL REFERENCES wallet(wallet_id),
  tx_type          VARCHAR(10) NOT NULL,
  source_type      VARCHAR(30) NOT NULL,
  source_ref_id    BIGINT NULL,
  amount           INT NOT NULL,
  balance_before   INT NOT NULL,
  balance_after    INT NOT NULL,
  idempotency_key  VARCHAR(100) NOT NULL,
  memo             VARCHAR(200) NULL,
  occurred_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_wallet_ledger_idem UNIQUE (idempotency_key),
  CONSTRAINT ck_wallet_ledger_tx_type CHECK (tx_type IN ('CREDIT','DEBIT')),
  CONSTRAINT ck_wallet_ledger_source_type CHECK (source_type IN ('PAYMENT','SUBSCRIPTION','AI','AD_CLICK','MANUAL'))
);

CREATE INDEX IF NOT EXISTS idx_wallet_ledger_wallet_occurred ON wallet_ledger(wallet_id, occurred_at DESC);


-- 13) subscription
CREATE TABLE IF NOT EXISTS subscription (
  subscription_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id      BIGINT NOT NULL REFERENCES employer(employer_id),
  product_id       BIGINT NOT NULL REFERENCES product(product_id),
  status           VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  started_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  next_billing_at  TIMESTAMPTZ(3) NULL,
  ended_at         TIMESTAMPTZ(3) NULL,
  customer_key     VARCHAR(80) NULL,
  billing_key      VARCHAR(200) NULL,
  card_company     VARCHAR(255) NULL,
  card_number      VARCHAR(255) NULL,
  next_product_id  BIGINT NULL REFERENCES product(product_id),
  created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT ck_subscription_status CHECK (status IN ('ACTIVE','CANCELED','PAYMENT_FAILED'))
);


-- 14) subscription_billing_cycle
CREATE TABLE IF NOT EXISTS subscription_billing_cycle (
  cycle_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id  BIGINT NOT NULL REFERENCES subscription(subscription_id),
  billing_month    DATE NOT NULL,
  payment_id       BIGINT NULL REFERENCES payment(payment_id),
  credit_grant     INT NOT NULL,
  ledger_id        BIGINT NULL REFERENCES wallet_ledger(ledger_id),
  payment_status   VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
  credit_status    VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_subscription_billing UNIQUE (subscription_id, billing_month),
  CONSTRAINT ck_cycle_payment_status CHECK (payment_status IN ('SCHEDULED','PAID','FAILED')),
  CONSTRAINT ck_cycle_credit_status CHECK (credit_status IN ('PENDING','GRANTED','FAILED','REVOKED'))
);


-- 15) job_posting
CREATE TABLE IF NOT EXISTS job_posting (
  job_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id         BIGINT NOT NULL REFERENCES employer(employer_id),
  title               VARCHAR(200) NOT NULL,
  description         TEXT NOT NULL,
  status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  location            VARCHAR(120) NULL,
  salary_text         VARCHAR(80) NULL,
  required_questions  JSONB NULL,
  view_count          INT NOT NULL DEFAULT 0,
  apply_count         INT NOT NULL DEFAULT 0,
  stack               TEXT[] NULL,
  required_experience INT NOT NULL DEFAULT 0,
  summary             TEXT NULL,
  embedding           vector(1536) NULL,
  ad_bid_credit       INT NOT NULL DEFAULT 0,
  recruitment_capacity INT NOT NULL DEFAULT 0,
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at          TIMESTAMPTZ(3) NULL,
  CONSTRAINT ck_job_posting_status CHECK (status IN ('DRAFT','OPEN','CLOSED')),
  CONSTRAINT ck_job_posting_counts CHECK (view_count >= 0 AND apply_count >= 0),
  CONSTRAINT ck_job_posting_ad_bid_credit_nonneg CHECK (ad_bid_credit >= 0),
  CONSTRAINT ck_job_posting_recruitment_capacity CHECK (recruitment_capacity >= 0)
);

CREATE INDEX IF NOT EXISTS idx_job_posting_employer_status ON job_posting(employer_id, status);
CREATE INDEX IF NOT EXISTS idx_job_posting_stack_gin ON job_posting USING GIN (stack);


-- 16) resume
CREATE TABLE IF NOT EXISTS resume (
  resume_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id            BIGINT NOT NULL REFERENCES member(member_id),
  title                VARCHAR(120) NOT NULL,
  tagline              VARCHAR(200) NULL,
  is_primary           BOOLEAN NOT NULL DEFAULT FALSE,
  is_public            BOOLEAN NOT NULL DEFAULT FALSE,
  status               VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  last_modified_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  created_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at           TIMESTAMPTZ(3) NULL,
  target_job_id        BIGINT NULL REFERENCES job_posting(job_id),
  content              TEXT NULL,
  field                VARCHAR(20) NOT NULL DEFAULT 'RESUME',
  summary              TEXT NULL,
  embedding            vector(1536) NULL,
  summary_status       VARCHAR(20) NOT NULL DEFAULT 'NONE',
  preference_location  VARCHAR(80) NULL,
  preference_salary    VARCHAR(80) NULL,
  employment_type      VARCHAR(80) NULL,
  re_stack             TEXT[] NULL,
  career_years         INT NOT NULL DEFAULT 0,
  school               TEXT NULL,
  school_state         TEXT NULL,
  school_class         TEXT NULL,
  CONSTRAINT ck_resume_status CHECK (status IN ('DRAFT','ACTIVE','DELETED')),
  CONSTRAINT ck_resume_field CHECK (field IN ('RESUME','PORTFOLIO','INTRO')),
  CONSTRAINT ck_resume_summary_status CHECK (summary_status IN ('NONE','PENDING','PROCESSING','COMPLETED','FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_resume_member_status ON resume(member_id, status);
CREATE INDEX IF NOT EXISTS idx_resume_re_stack_gin ON resume USING GIN (re_stack);


-- 17) job_application
CREATE TABLE IF NOT EXISTS job_application (
  application_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id                BIGINT NOT NULL REFERENCES job_posting(job_id),
  member_id             BIGINT NOT NULL REFERENCES member(member_id),
  resume_id             BIGINT NOT NULL REFERENCES resume(resume_id),
  status                VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
  answers               JSONB NULL,
  applied_at            TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  canceled_at           TIMESTAMPTZ(3) NULL,
  viewed_at             TIMESTAMPTZ(3) NULL,
  contact_disclosed_at  TIMESTAMPTZ(3) NULL,
  created_at            TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_job_application UNIQUE (job_id, member_id),
  CONSTRAINT ck_job_application_status CHECK (status IN ('SUBMITTED','VIEWED','INTERVIEW','HIRED','REJECTED','CANCELED'))
);


-- 18) interview_schedule
CREATE TABLE IF NOT EXISTS interview_schedule (
  interview_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id       BIGINT NOT NULL REFERENCES job_application(application_id),
  stage                VARCHAR(20) NOT NULL,
  method               VARCHAR(20) NOT NULL,
  location             VARCHAR(200) NULL,
  meeting_url          TEXT NULL,
  start_at             TIMESTAMPTZ(3) NOT NULL,
  end_at               TIMESTAMPTZ(3) NOT NULL,
  status               VARCHAR(20) NOT NULL DEFAULT 'PROPOSED',
  created_by_member_id BIGINT NULL REFERENCES member(member_id),
  created_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT ck_interview_stage CHECK (stage IN ('1ST','2ND','FINAL')),
  CONSTRAINT ck_interview_method CHECK (method IN ('ONSITE','VIDEO','PHONE')),
  CONSTRAINT ck_interview_status CHECK (status IN ('PROPOSED','CONFIRMED','CANCELED','DONE')),
  CONSTRAINT ck_interview_time CHECK (end_at > start_at)
);


-- 19) interview_response
CREATE TABLE IF NOT EXISTS interview_response (
  response_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interview_id    BIGINT NOT NULL REFERENCES interview_schedule(interview_id),
  response        VARCHAR(20) NOT NULL,
  message         TEXT NULL,
  responded_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT ck_interview_response CHECK (response IN ('ACCEPT','DECLINE','REQUEST_CHANGE'))
);


-- 20) resume_profile
CREATE TABLE IF NOT EXISTS resume_profile (
  profile_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id    BIGINT NOT NULL REFERENCES resume(resume_id),
  address      VARCHAR(200) NULL,
  photo_url    TEXT NULL,
  created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_resume_profile UNIQUE (resume_id)
);


-- 21) resume_project
CREATE TABLE IF NOT EXISTS resume_project (
  project_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id           BIGINT NOT NULL REFERENCES resume(resume_id),
  title               VARCHAR(120) NOT NULL,
  start_date          DATE NULL,
  end_date            DATE NULL,
  contribution_pct    NUMERIC(5,2) NULL,
  tech_stack          TEXT[] NULL,
  description         TEXT NULL,
  sort_order          INT NOT NULL DEFAULT 0,
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);


-- 22) resume_attachment
CREATE TABLE IF NOT EXISTS resume_attachment (
  attachment_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id       BIGINT NOT NULL REFERENCES resume(resume_id),
  file_url        TEXT NOT NULL,
  file_name       VARCHAR(200) NOT NULL,
  mime_type       VARCHAR(80) NULL,
  file_size       BIGINT NULL,
  scan_status     VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  copyright_ok    BOOLEAN NOT NULL DEFAULT FALSE,
  ai_description  TEXT NULL,
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT ck_resume_attachment_scan_status CHECK (scan_status IN ('PENDING','PASSED','FAILED'))
);


-- 23) resume_link
CREATE TABLE IF NOT EXISTS resume_link (
  link_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id    BIGINT NOT NULL REFERENCES resume(resume_id),
  link_type    VARCHAR(20) NOT NULL,
  url          TEXT NOT NULL,
  created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT ck_resume_link_type CHECK (link_type IN ('GITHUB','BLOG','ETC'))
);


-- 24) resume_career
CREATE TABLE IF NOT EXISTS resume_career (
  career_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id       BIGINT NOT NULL REFERENCES resume(resume_id),
  company_name    VARCHAR(100) NOT NULL,
  department      VARCHAR(100) NOT NULL,
  role            VARCHAR(100) NOT NULL,
  start_date      DATE NOT NULL,
  end_date        DATE NULL,
  is_current      BOOLEAN NULL,
  is_verified     BOOLEAN NULL,
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_resume_career_resume_id ON resume_career(resume_id);


-- 25) resume_certificate
CREATE TABLE IF NOT EXISTS resume_certificate (
  resume_certificate_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id              BIGINT NOT NULL REFERENCES resume(resume_id),
  name                   VARCHAR(100) NOT NULL,
  issuer                 VARCHAR(100) NOT NULL,
  acquisition_date       DATE NOT NULL,
  is_verified            BOOLEAN NULL,
  created_at             TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_resume_certificate_resume_id ON resume_certificate(resume_id);


-- 26) job_scrap
CREATE TABLE IF NOT EXISTS job_scrap (
  scrap_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id    BIGINT NOT NULL REFERENCES member(member_id),
  job_id       BIGINT NOT NULL REFERENCES job_posting(job_id),
  created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_job_scrap UNIQUE (member_id, job_id)
);


-- 27) job_view_log
CREATE TABLE IF NOT EXISTS job_view_log (
  view_log_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id    BIGINT NULL REFERENCES member(member_id),
  job_id       BIGINT NOT NULL REFERENCES job_posting(job_id),
  viewed_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);


-- 28) ad_campaign
CREATE TABLE IF NOT EXISTS ad_campaign (
  campaign_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id    BIGINT NOT NULL REFERENCES employer(employer_id),
  job_id         BIGINT NOT NULL REFERENCES job_posting(job_id),
  cpc_bid        INT NOT NULL,
  daily_budget   INT NOT NULL,
  status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  start_at       TIMESTAMPTZ(3) NULL,
  end_at         TIMESTAMPTZ(3) NULL,
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT ck_ad_campaign_status CHECK (status IN ('ACTIVE','PAUSED','ENDED'))
);


-- 29) ad_click_event
CREATE TABLE IF NOT EXISTS ad_click_event (
  click_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id   BIGINT NOT NULL REFERENCES ad_campaign(campaign_id),
  member_id     BIGINT NULL REFERENCES member(member_id),
  click_key     VARCHAR(120) NOT NULL,
  ledger_id     BIGINT NULL REFERENCES wallet_ledger(ledger_id),
  occurred_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_ad_click_key UNIQUE (click_key)
);


-- 30) inquiry
CREATE TABLE IF NOT EXISTS inquiry (
  inquiry_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id        BIGINT NOT NULL REFERENCES member(member_id),
  title            VARCHAR(200) NOT NULL,
  status           VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  answered_at      TIMESTAMPTZ(3) NULL,
  retention_until  TIMESTAMPTZ(3) NULL,
  created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT ck_inquiry_status CHECK (status IN ('OPEN','ANSWERED','CLOSED'))
);


-- 31) inquiry_message
CREATE TABLE IF NOT EXISTS inquiry_message (
  message_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inquiry_id           BIGINT NOT NULL REFERENCES inquiry(inquiry_id),
  author_type          VARCHAR(20) NOT NULL,
  admin_member_id      BIGINT NULL REFERENCES member(member_id),
  body                 TEXT NOT NULL,
  created_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT ck_inquiry_author_type CHECK (author_type IN ('CUSTOMER','ADMIN'))
);


-- 32) notice_attachment
CREATE TABLE IF NOT EXISTS notice_attachment (
  attachment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id      BIGINT NOT NULL REFERENCES notice(notice_id),
  file_url       TEXT NOT NULL,
  file_name      VARCHAR(200) NOT NULL,
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);


-- 33) notice_delivery
CREATE TABLE IF NOT EXISTS notice_delivery (
  delivery_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id     BIGINT NOT NULL REFERENCES notice(notice_id),
  member_id     BIGINT NOT NULL REFERENCES member(member_id),
  channel       VARCHAR(20) NOT NULL,
  status        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  sent_at       TIMESTAMPTZ(3) NULL,
  fail_reason   VARCHAR(200) NULL,
  created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT ck_notice_delivery_channel CHECK (channel IN ('EMAIL','SMS','LMS','PUSH')),
  CONSTRAINT ck_notice_delivery_status CHECK (status IN ('PENDING','SENT','FAILED'))
);


-- 34) faq
CREATE TABLE IF NOT EXISTS faq (
  faq_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question    TEXT NOT NULL,
  answer      TEXT NOT NULL,
  locked      BOOLEAN NOT NULL DEFAULT TRUE,
  is_public   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ(3) NULL
);


-- 35) report
CREATE TABLE IF NOT EXISTS report (
  report_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_member_id  BIGINT NOT NULL REFERENCES member(member_id),
  target_type         VARCHAR(20) NOT NULL,
  target_job_id       BIGINT NULL REFERENCES job_posting(job_id),
  reason_code         VARCHAR(30) NOT NULL,
  reason_detail       TEXT NULL,
  status              VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT ck_report_target_type CHECK (target_type IN ('JOB_POSTING','MEMBER','ETC')),
  CONSTRAINT ck_report_status CHECK (status IN ('OPEN','ACCEPTED','REJECTED'))
);


-- 36) moderation_action
CREATE TABLE IF NOT EXISTS moderation_action (
  action_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id        BIGINT NOT NULL REFERENCES report(report_id),
  admin_member_id  BIGINT NULL REFERENCES member(member_id),
  decision         VARCHAR(20) NOT NULL,
  sanction_level   INT NULL,
  restrict_days    INT NULL,
  reason           TEXT NOT NULL,
  decided_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_moderation_action_report UNIQUE (report_id),
  CONSTRAINT ck_moderation_decision CHECK (decision IN ('ACCEPT','REJECT'))
);


-- 37) member_penalty_point
CREATE TABLE IF NOT EXISTS member_penalty_point (
  penalty_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id    BIGINT NOT NULL REFERENCES member(member_id),
  report_id    BIGINT NULL REFERENCES report(report_id),
  points       INT NOT NULL,
  reason       VARCHAR(200) NOT NULL,
  created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);


-- 38) notification_template
CREATE TABLE IF NOT EXISTS notification_template (
  template_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_code  VARCHAR(50) NOT NULL,
  channel        VARCHAR(20) NOT NULL,
  subject        VARCHAR(200) NULL,
  body           TEXT NOT NULL,
  created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_notification_template_code UNIQUE (template_code),
  CONSTRAINT ck_notification_channel CHECK (channel IN ('EMAIL','SMS','PUSH'))
);


-- 39) notification_delivery
CREATE TABLE IF NOT EXISTS notification_delivery (
  delivery_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id   BIGINT NULL REFERENCES notification_template(template_id),
  member_id     BIGINT NOT NULL REFERENCES member(member_id),
  event_type    VARCHAR(40) NOT NULL,
  channel       VARCHAR(20) NOT NULL,
  status        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  sent_at       TIMESTAMPTZ(3) NULL,
  payload       JSONB NULL,
  created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT ck_notification_delivery_status CHECK (status IN ('PENDING','SENT','FAILED')),
  CONSTRAINT ck_notification_delivery_channel CHECK (channel IN ('EMAIL','SMS','PUSH'))
);


-- 40) outbox_event
CREATE TABLE IF NOT EXISTS outbox_event (
  outbox_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type      VARCHAR(50) NOT NULL,
  aggregate_type  VARCHAR(30) NOT NULL,
  aggregate_id    BIGINT NOT NULL,
  payload         JSONB NOT NULL,
  status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  retry_count     INT NOT NULL DEFAULT 0,
  next_run_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  locked_at       TIMESTAMPTZ(3) NULL,
  locked_by       VARCHAR(80) NULL,
  last_error      TEXT NULL,
  created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  processed_at    TIMESTAMPTZ(3) NULL,
  CONSTRAINT ck_outbox_status CHECK (status IN ('PENDING','PROCESSING','SUCCEEDED','FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_outbox_pick ON outbox_event(status, next_run_at, outbox_id);
CREATE INDEX IF NOT EXISTS idx_outbox_agg ON outbox_event(aggregate_type, aggregate_id);


-- 41) wallet_credit_lot
CREATE TABLE IF NOT EXISTS wallet_credit_lot (
  lot_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id           BIGINT NOT NULL REFERENCES wallet(wallet_id),
  payment_id          BIGINT NOT NULL REFERENCES payment(payment_id),
  granted_credit      INT NOT NULL,
  remaining_credit    INT NOT NULL,
  unit_price_amount   NUMERIC(12,2) NOT NULL,
  currency            CHAR(3) NOT NULL DEFAULT 'KRW',
  pricing_meta        JSONB NULL,
  created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_wallet_credit_lot_wallet_payment ON wallet_credit_lot(wallet_id, payment_id);
CREATE INDEX IF NOT EXISTS idx_wallet_credit_lot_wallet_created ON wallet_credit_lot(wallet_id, created_at ASC);


-- 42) payment_cancel
CREATE TABLE IF NOT EXISTS payment_cancel (
  cancel_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id             BIGINT NOT NULL REFERENCES payment(payment_id),
  toss_transaction_key   VARCHAR(80) NOT NULL,
  cancel_status          VARCHAR(40) NULL,
  cancel_amount          NUMERIC(12,2) NOT NULL,
  cancel_reason          VARCHAR(200) NOT NULL,
  canceled_at            TIMESTAMPTZ(3) NULL,
  idempotency_key        VARCHAR(100) NOT NULL,
  raw_cancel             JSONB NULL,
  created_at             TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_payment_cancel_tx UNIQUE (payment_id, toss_transaction_key),
  CONSTRAINT uq_payment_cancel_idem UNIQUE (idempotency_key),
  CONSTRAINT ck_payment_cancel_amount CHECK (cancel_amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_payment_cancel_payment_created ON payment_cancel(payment_id, created_at DESC);


-- 43) stack_alias (기술스택 별칭)
CREATE TABLE IF NOT EXISTS stack_alias (
  entity_type  TEXT NOT NULL DEFAULT 'STACK',
  alias        TEXT NOT NULL,
  canonical    TEXT NOT NULL,
  display_name TEXT,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (entity_type, alias),
  CONSTRAINT stack_alias_entity_type_chk CHECK (entity_type IN ('STACK','INDUSTRY'))
);

CREATE INDEX IF NOT EXISTS ix_stack_alias_alias_trgm_stack ON stack_alias USING gin (alias gin_trgm_ops) WHERE is_active AND entity_type='STACK';
CREATE INDEX IF NOT EXISTS ix_stack_alias_canonical_trgm_stack ON stack_alias USING gin (canonical gin_trgm_ops) WHERE is_active AND entity_type='STACK';


-- 44) industry_alias (업종 별칭)
CREATE TABLE IF NOT EXISTS industry_alias (
  alias        TEXT PRIMARY KEY,
  canonical    TEXT NOT NULL,
  display_name TEXT NULL,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_industry_alias_alias_trgm ON industry_alias USING gin (alias gin_trgm_ops) WHERE is_active;
CREATE INDEX IF NOT EXISTS ix_industry_alias_canonical_trgm ON industry_alias USING gin (canonical gin_trgm_ops) WHERE is_active;


-- 45) talent_proposal (기업→구직자 제안)
CREATE TABLE IF NOT EXISTS talent_proposal (
  proposal_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id       BIGINT NOT NULL REFERENCES employer(employer_id),
  candidate_id      BIGINT NOT NULL REFERENCES member(member_id),
  job_id            BIGINT NULL REFERENCES job_posting(job_id),
  status            VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  title             VARCHAR(200) NOT NULL,
  message           TEXT NULL,
  offered_salary    VARCHAR(100) NULL,
  offered_position  VARCHAR(100) NULL,
  expires_at        TIMESTAMPTZ(3) NULL,
  viewed_at         TIMESTAMPTZ(3) NULL,
  responded_at      TIMESTAMPTZ(3) NULL,
  response_message  TEXT NULL,
  created_at        TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  CONSTRAINT uq_talent_proposal UNIQUE (employer_id, candidate_id, job_id),
  CONSTRAINT ck_talent_proposal_status CHECK (status IN ('PENDING','VIEWED','ACCEPTED','REJECTED','CANCELED','EXPIRED'))
);

CREATE INDEX IF NOT EXISTS idx_talent_proposal_candidate ON talent_proposal(candidate_id, status);
CREATE INDEX IF NOT EXISTS idx_talent_proposal_employer ON talent_proposal(employer_id, status);


-- 46) industry_vocab (Materialized View - fuzzy 검색용)
DROP MATERIALIZED VIEW IF EXISTS industry_vocab;
CREATE MATERIALIZED VIEW industry_vocab AS
WITH tokens AS (
  SELECT lower(btrim(tok)) AS token
  FROM industry_alias ia
  CROSS JOIN LATERAL regexp_split_to_table(
    coalesce(ia.alias,'') || ',' || coalesce(ia.canonical,''),
    '\s*[,/|]+\s*'
  ) AS tok
  WHERE ia.is_active
)
SELECT token, COUNT(*)::bigint AS cnt
FROM tokens
WHERE token <> ''
GROUP BY token;

CREATE UNIQUE INDEX IF NOT EXISTS ux_industry_vocab_token ON industry_vocab (token);
CREATE INDEX IF NOT EXISTS ix_industry_vocab_token_trgm ON industry_vocab USING gin (token gin_trgm_ops);


-- ================================================================
-- PART 3: 트리거 생성
-- ================================================================
DO $$
DECLARE t text;
BEGIN
    FOR t IN SELECT unnest(ARRAY[
        'member', 'employer', 'product', 'orders', 'payment', 'wallet',
        'subscription', 'job_posting', 'resume', 'job_application',
        'interview_schedule', 'resume_project', 'resume_career',
        'resume_certificate', 'inquiry', 'notice', 'faq', 'ad_campaign',
        'outbox_event', 'wallet_credit_lot', 'phone_verification',
        'member_login_log', 'employer_member', 'subscription_billing_cycle',
        'interview_response', 'resume_profile', 'resume_attachment',
        'resume_link', 'job_scrap', 'job_view_log', 'ad_click_event',
        'inquiry_message', 'notice_attachment', 'notice_delivery',
        'report', 'moderation_action', 'member_penalty_point',
        'notification_template', 'payment_cancel', 'stack_alias',
        'industry_alias', 'talent_proposal'
    ])
    LOOP
        IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_set_updated_at_' || t) THEN
            EXECUTE format('CREATE TRIGGER trg_set_updated_at_%I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()', t, t);
        END IF;
    END LOOP;
END $$;


-- ================================================================
-- PART 4: 필수 초기 데이터
-- ================================================================

-- 약관/개인정보 동의용 notice (member 가입 시 필수 참조)
INSERT INTO notice (notice_id, title, body, is_public, notice_type, status)
VALUES 
    (1, '서비스 이용약관', '서비스 이용약관 내용입니다.', TRUE, 'TERMS', 'ACTIVE'),
    (2, '개인정보 처리방침', '개인정보 처리방침 내용입니다.', TRUE, 'PRIVACY', 'ACTIVE'),
    (3, '운영정책', '운영정책 내용입니다.', TRUE, 'POLICY', 'ACTIVE')
ON CONFLICT (notice_id) DO UPDATE SET
    title = EXCLUDED.title,
    body = EXCLUDED.body,
    notice_type = EXCLUDED.notice_type;

-- notice_id 시퀀스 동기화
SELECT setval(pg_get_serial_sequence('notice', 'notice_id'), GREATEST(COALESCE(MAX(notice_id), 1), 3)) FROM notice;

-- 상품 데이터 (결제 시 필요)
INSERT INTO product (product_code, product_type, name, sale_status, price_amount, currency, credit_amount, plan_tier)
VALUES
    ('CREDIT_100', 'ONE_TIME', '크레딧 100', 'ON_SALE', 10000.00, 'KRW', 100, NULL),
    ('CREDIT_500', 'ONE_TIME', '크레딧 500', 'ON_SALE', 45000.00, 'KRW', 500, NULL),
    ('CREDIT_1000', 'ONE_TIME', '크레딧 1000', 'ON_SALE', 80000.00, 'KRW', 1000, NULL),
    ('SUB_BASIC', 'SUBSCRIPTION', '베이직 구독', 'ON_SALE', 29000.00, 'KRW', 50, 'BASIC'),
    ('SUB_PRO', 'SUBSCRIPTION', '프로 구독', 'ON_SALE', 99000.00, 'KRW', 200, 'PRO'),
    ('SUB_ENTERPRISE', 'SUBSCRIPTION', '엔터프라이즈 구독', 'ON_SALE', 299000.00, 'KRW', 1000, 'ENTERPRISE')
ON CONFLICT (product_code) DO UPDATE SET
    name = EXCLUDED.name,
    price_amount = EXCLUDED.price_amount,
    credit_amount = EXCLUDED.credit_amount,
    plan_tier = EXCLUDED.plan_tier;

-- 알림 템플릿
INSERT INTO notification_template (template_code, channel, subject, body) VALUES
    ('INTERVIEW_SCHEDULED', 'EMAIL', '면접 일정이 확정되었습니다', '{{company_name}}과의 {{stage}} 면접이 {{date}}에 예정되었습니다.'),
    ('INTERVIEW_REMINDER', 'PUSH', '면접 리마인더', '{{company_name}} 면접이 1시간 후에 시작됩니다.'),
    ('APPLICATION_VIEWED', 'PUSH', '이력서 열람 알림', '{{company_name}}에서 회원님의 이력서를 열람했습니다.'),
    ('APPLICATION_STATUS', 'EMAIL', '지원 현황 업데이트', '{{company_name}}에 지원하신 {{job_title}} 포지션의 상태가 업데이트되었습니다.'),
    ('NEW_JOB_MATCH', 'PUSH', '새로운 채용공고 추천', '회원님의 프로필과 맞는 새로운 채용공고가 등록되었습니다.')
ON CONFLICT (template_code) DO UPDATE SET
    channel = EXCLUDED.channel,
    subject = EXCLUDED.subject,
    body = EXCLUDED.body;

-- FAQ (없을 때만 삽입)
INSERT INTO faq (question, answer, locked, is_public)
SELECT * FROM (VALUES
    ('회원가입은 어떻게 하나요?', '홈페이지 우측 상단의 "회원가입" 버튼을 클릭하여 이메일 또는 소셜 로그인으로 가입하실 수 있습니다.', TRUE, TRUE),
    ('이력서는 몇 개까지 등록할 수 있나요?', '최대 5개의 이력서를 등록하실 수 있습니다.', TRUE, TRUE),
    ('채용공고 등록 비용은 어떻게 되나요?', '기본 채용공고 등록은 무료이며, 프리미엄 노출은 크레딧을 사용합니다.', TRUE, TRUE),
    ('크레딧은 어떻게 충전하나요?', '마이페이지 > 크레딧 충전 메뉴에서 충전하실 수 있습니다.', TRUE, TRUE),
    ('지원 취소는 어떻게 하나요?', '마이페이지 > 지원현황에서 "지원 취소" 버튼을 클릭하시면 됩니다.', TRUE, TRUE)
) AS v(question, answer, locked, is_public)
WHERE NOT EXISTS (SELECT 1 FROM faq WHERE faq.question = v.question);

-- 기술스택 별칭
INSERT INTO stack_alias (entity_type, alias, canonical, display_name) VALUES
    ('STACK', 'node', 'nodejs', 'Node.js'),
    ('STACK', 'node.js', 'nodejs', 'Node.js'),
    ('STACK', 'vue', 'vuejs', 'Vue.js'),
    ('STACK', 'vue.js', 'vuejs', 'Vue.js'),
    ('STACK', 'next', 'nextjs', 'Next.js'),
    ('STACK', 'next.js', 'nextjs', 'Next.js')
ON CONFLICT (entity_type, alias) DO UPDATE SET canonical = EXCLUDED.canonical, display_name = EXCLUDED.display_name, is_active = TRUE;

-- 업종 별칭
INSERT INTO industry_alias (alias, canonical, display_name) VALUES
    ('it', 'it', 'IT'),
    ('it서비스', 'it', 'IT'),
    ('웹서비스', 'it', 'IT'),
    ('ai', 'ai', 'AI'),
    ('인공지능', 'ai', 'AI'),
    ('데이터', 'data', 'Data'),
    ('데이터서비스', 'data', 'Data'),
    ('mobile', 'mobile', 'Mobile'),
    ('모바일', 'mobile', 'Mobile'),
    ('fintech', 'fintech', 'Fintech'),
    ('핀테크', 'fintech', 'Fintech'),
    ('ecommerce', 'ecommerce', 'E-Commerce'),
    ('이커머스', 'ecommerce', 'E-Commerce'),
    ('커머스', 'ecommerce', 'E-Commerce'),
    ('게임', 'game', 'Game'),
    ('game', 'game', 'Game'),
    ('헬스케어', 'healthcare', 'Healthcare'),
    ('healthcare', 'healthcare', 'Healthcare'),
    ('edtech', 'edtech', 'EdTech'),
    ('에듀테크', 'edtech', 'EdTech')
ON CONFLICT (alias) DO UPDATE SET canonical = EXCLUDED.canonical, display_name = EXCLUDED.display_name, is_active = TRUE;

-- industry_vocab 갱신
REFRESH MATERIALIZED VIEW industry_vocab;


-- ================================================================
-- 완료!
-- ================================================================
