package com.example.pproject.outbox.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;

/**
 * 아웃박스 이벤트 엔티티
 * 
 * ========================================
 * ERD 테이블: outbox_event (39번)
 * ========================================
 * 
 * 컬럼 매핑:
 * - outbox_id      -> id (PK, BIGINT GENERATED BY DEFAULT AS IDENTITY)
 * - event_type     -> eventType (VARCHAR(50) NOT NULL)
 * - aggregate_type -> aggregateType (VARCHAR(30) NOT NULL)
 * - aggregate_id   -> aggregateId (BIGINT NOT NULL)
 * - payload        -> payload (JSONB NOT NULL)
 * - status         -> status (VARCHAR(20) NOT NULL DEFAULT 'PENDING')
 * - retry_count    -> retryCount (INT NOT NULL DEFAULT 0)
 * - next_run_at    -> nextRunAt (TIMESTAMPTZ(3) NOT NULL DEFAULT now())
 * - locked_at      -> lockedAt (TIMESTAMPTZ(3) NULL)
 * - locked_by      -> lockedBy (VARCHAR(80) NULL)
 * - last_error     -> lastError (TEXT NULL)
 * - created_at     -> createdAt (TIMESTAMPTZ(3) NOT NULL DEFAULT now())
 * - updated_at     -> updatedAt (TIMESTAMPTZ(3) NOT NULL DEFAULT now())
 * - processed_at   -> processedAt (TIMESTAMPTZ(3) NULL)
 * 
 * 제약조건:
 * - CONSTRAINT ck_outbox_status CHECK (status IN ('PENDING','PROCESSING','SUCCEEDED','FAILED'))
 * 
 * 인덱스:
 * - idx_outbox_pick: (status, next_run_at, outbox_id) - Worker가 처리할 이벤트 조회용
 * - idx_outbox_agg: (aggregate_type, aggregate_id) - 특정 엔티티의 이벤트 조회용
 */
@Entity
@Table(name = "outbox_event", indexes = {
        @Index(name = "idx_outbox_pick", columnList = "status, next_run_at, outbox_id"),
        @Index(name = "idx_outbox_agg", columnList = "aggregate_type, aggregate_id")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OutboxEvent {

    /**
     * PK: outbox_id (BIGINT GENERATED BY DEFAULT AS IDENTITY)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "outbox_id")
    private Long id;

    /**
     * 이벤트 타입 (VARCHAR(50) NOT NULL)
     * - 발생한 이벤트의 종류
     * - 예: JOB_POSTING_CREATED, APPLICATION_SUBMITTED, INTERVIEW_SCHEDULED 등
     */
    @Column(name = "event_type", nullable = false, length = 50)
    private String eventType;

    /**
     * 집합체 타입 (VARCHAR(30) NOT NULL)
     * - 이벤트가 발생한 도메인 엔티티 타입
     * - 예: JOB_POSTING, APPLICATION, INTERVIEW, PAYMENT 등
     */
    @Column(name = "aggregate_type", nullable = false, length = 30)
    private String aggregateType;

    /**
     * 집합체 ID (BIGINT NOT NULL)
     * - 이벤트가 발생한 엔티티의 PK
     * - 예: job_id, application_id, interview_id 등
     */
    @Column(name = "aggregate_id", nullable = false)
    private Long aggregateId;

    /**
     * 페이로드 (JSONB NOT NULL)
     * - 이벤트 상세 데이터 (JSON 형식)
     * - 예: {"jobId": 123, "title": "백엔드 개발자", "companyName": "ABC"}
     * - Hibernate 6: @JdbcTypeCode(SqlTypes.JSON) 필수
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "payload", columnDefinition = "JSONB", nullable = false)
    private String payload;

    /**
     * 처리 상태 (VARCHAR(20) NOT NULL DEFAULT 'PENDING')
     * - CHECK: PENDING, PROCESSING, SUCCEEDED, FAILED
     */
    @Column(name = "status", nullable = false, length = 20)
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private OutboxStatus status = OutboxStatus.PENDING;

    /**
     * 재시도 횟수 (INT NOT NULL DEFAULT 0)
     * - 실패 시 재시도한 횟수
     */
    @Column(name = "retry_count", nullable = false)
    @Builder.Default
    private Integer retryCount = 0;

    /**
     * 다음 실행 시각 (TIMESTAMPTZ(3) NOT NULL DEFAULT now())
     * - 재시도 시 백오프 적용된 다음 실행 시각
     */
    @Column(name = "next_run_at", nullable = false)
    private Instant nextRunAt;

    /**
     * 락 획득 시각 (TIMESTAMPTZ(3) NULL)
     * - Worker가 처리를 위해 락을 획득한 시각
     */
    @Column(name = "locked_at")
    private Instant lockedAt;

    /**
     * 락 소유자 (VARCHAR(80) NULL)
     * - 락을 획득한 Worker 식별자
     * - 예: worker-1, scheduler-pod-abc123
     */
    @Column(name = "locked_by", length = 80)
    private String lockedBy;

    /**
     * 마지막 에러 (TEXT NULL)
     * - 처리 실패 시 에러 메시지
     */
    @Column(name = "last_error", columnDefinition = "TEXT")
    private String lastError;

    /**
     * 생성일시 (TIMESTAMPTZ(3) NOT NULL DEFAULT now())
     */
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    /**
     * 수정일시 (TIMESTAMPTZ(3) NOT NULL DEFAULT now())
     * - 트리거로 자동 갱신: trg_set_updated_at_outbox_event
     */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * 처리 완료 시각 (TIMESTAMPTZ(3) NULL)
     * - 이벤트 처리가 완료된 시각
     */
    @Column(name = "processed_at")
    private Instant processedAt;

    @PrePersist
    void prePersist() {
        Instant now = Instant.now();
        if (createdAt == null) createdAt = now;
        if (updatedAt == null) updatedAt = now;
        if (nextRunAt == null) nextRunAt = now;
        if (status == null) status = OutboxStatus.PENDING;
        if (retryCount == null) retryCount = 0;
    }

    @PreUpdate
    void preUpdate() {
        updatedAt = Instant.now();
    }

    /**
     * 아웃박스 상태 Enum
     * - ERD CHECK: status IN ('PENDING','PROCESSING','SUCCEEDED','FAILED')
     */
    public enum OutboxStatus {
        PENDING,     // 처리 대기
        PROCESSING,  // 처리 중 (락 획득)
        SUCCEEDED,   // 처리 성공
        FAILED       // 처리 실패 (재시도 소진)
    }

    // ==================== 비즈니스 메서드 ====================

    /**
     * 처리 시작 (락 획득)
     * 
     * @param workerId Worker 식별자
     */
    public void startProcessing(String workerId) {
        this.status = OutboxStatus.PROCESSING;
        this.lockedAt = Instant.now();
        this.lockedBy = workerId;
    }

    /**
     * 처리 성공
     */
    public void markAsSucceeded() {
        this.status = OutboxStatus.SUCCEEDED;
        this.processedAt = Instant.now();
        this.lockedAt = null;
        this.lockedBy = null;
    }

    /**
     * 처리 실패 (재시도 가능)
     * 
     * @param error 에러 메시지
     * @param maxRetries 최대 재시도 횟수
     */
    public void markAsFailed(String error, int maxRetries) {
        this.retryCount++;
        this.lastError = error;
        this.lockedAt = null;
        this.lockedBy = null;

        if (this.retryCount >= maxRetries) {
            this.status = OutboxStatus.FAILED;
        } else {
            this.status = OutboxStatus.PENDING;
            // 지수 백오프: 2^retryCount * 1분
            long delayMinutes = (long) Math.pow(2, this.retryCount);
            this.nextRunAt = Instant.now().plusSeconds(delayMinutes * 60);
        }
    }

    /**
     * 락 해제 (타임아웃 등)
     */
    public void releaseLock() {
        this.lockedAt = null;
        this.lockedBy = null;
        this.status = OutboxStatus.PENDING;
    }

    /**
     * 락 만료 여부 확인
     * 
     * @param timeoutMinutes 타임아웃 (분)
     * @return 만료 여부
     */
    public boolean isLockExpired(int timeoutMinutes) {
        if (lockedAt == null) return false;
        return lockedAt.plusSeconds(timeoutMinutes * 60L).isBefore(Instant.now());
    }
}
