name: FIT ME Backend CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      # (1) 소스 코드 가져오기
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # (2) Java 21 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # (3) Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # (4) 빌드 및 테스트 실행
      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: 'backend/build/test-results/test/TEST-*.xml'